// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.webflow.UserArgs;
import io.github.jdetmar.webflow.Utilities;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages users for a Webflow site. This resource allows you to invite users to your site with specified access groups. Users will receive an invitation email and must accept it to access paid content. Note: The user&#39;s email cannot be changed after creation.
 * 
 */
@ResourceType(type="webflow:index:User")
public class User extends com.pulumi.resources.CustomResource {
    /**
     * Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type &#39;admin&#39; (assigned via API or designer). Example: [&#39;premium-members&#39;, &#39;beta-testers&#39;]. Access group slugs can be found in the Webflow dashboard under Users &gt; Access Groups.
     * 
     */
    @Export(name="accessGroups", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> accessGroups;

    /**
     * @return Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type &#39;admin&#39; (assigned via API or designer). Example: [&#39;premium-members&#39;, &#39;beta-testers&#39;]. Access group slugs can be found in the Webflow dashboard under Users &gt; Access Groups.
     * 
     */
    public Output<Optional<List<String>>> accessGroups() {
        return Codegen.optional(this.accessGroups);
    }
    /**
     * The timestamp when the user was created (RFC3339 format). This is automatically set and is read-only.
     * 
     */
    @Export(name="createdOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdOn;

    /**
     * @return The timestamp when the user was created (RFC3339 format). This is automatically set and is read-only.
     * 
     */
    public Output<Optional<String>> createdOn() {
        return Codegen.optional(this.createdOn);
    }
    /**
     * The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
     * 
     */
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output<String> email;

    /**
     * @return The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
     * 
     */
    public Output<String> email() {
        return this.email;
    }
    /**
     * The timestamp when the user was invited (RFC3339 format). This is automatically set and is read-only.
     * 
     */
    @Export(name="invitedOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> invitedOn;

    /**
     * @return The timestamp when the user was invited (RFC3339 format). This is automatically set and is read-only.
     * 
     */
    public Output<Optional<String>> invitedOn() {
        return Codegen.optional(this.invitedOn);
    }
    /**
     * Indicates whether the user has verified their email address. This is read-only and set by Webflow when the user verifies their email.
     * 
     */
    @Export(name="isEmailVerified", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isEmailVerified;

    /**
     * @return Indicates whether the user has verified their email address. This is read-only and set by Webflow when the user verifies their email.
     * 
     */
    public Output<Optional<Boolean>> isEmailVerified() {
        return Codegen.optional(this.isEmailVerified);
    }
    /**
     * The timestamp when the user last logged in (RFC3339 format). This is read-only.
     * 
     */
    @Export(name="lastLogin", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastLogin;

    /**
     * @return The timestamp when the user last logged in (RFC3339 format). This is read-only.
     * 
     */
    public Output<Optional<String>> lastLogin() {
        return Codegen.optional(this.lastLogin);
    }
    /**
     * The timestamp when the user was last updated (RFC3339 format). This is read-only.
     * 
     */
    @Export(name="lastUpdated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastUpdated;

    /**
     * @return The timestamp when the user was last updated (RFC3339 format). This is read-only.
     * 
     */
    public Output<Optional<String>> lastUpdated() {
        return Codegen.optional(this.lastUpdated);
    }
    /**
     * Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> name;

    /**
     * @return Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
     * 
     */
    public Output<Optional<String>> name() {
        return Codegen.optional(this.name);
    }
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Export(name="siteId", refs={String.class}, tree="[0]")
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }
    /**
     * The status of the user. Possible values: &#39;invited&#39; (invitation sent but not accepted), &#39;verified&#39; (email verified), &#39;unverified&#39; (registered but email not verified). This is read-only.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> status;

    /**
     * @return The status of the user. Possible values: &#39;invited&#39; (invitation sent but not accepted), &#39;verified&#39; (email verified), &#39;unverified&#39; (registered but email not verified). This is read-only.
     * 
     */
    public Output<Optional<String>> status() {
        return Codegen.optional(this.status);
    }
    /**
     * The Webflow-assigned unique identifier for this user. This is automatically assigned when the user is created and is read-only.
     * 
     */
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> userId;

    /**
     * @return The Webflow-assigned unique identifier for this user. This is automatically assigned when the user is created and is read-only.
     * 
     */
    public Output<Optional<String>> userId() {
        return Codegen.optional(this.userId);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public User(java.lang.String name) {
        this(name, UserArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public User(java.lang.String name, UserArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public User(java.lang.String name, UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:User", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private User(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:User", name, null, makeResourceOptions(options, id), false);
    }

    private static UserArgs makeArgs(UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? UserArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static User get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new User(name, id, options);
    }
}
