// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import io.github.jdetmar.webflow.Utilities;
import io.github.jdetmar.webflow.inputs.GetAuthorizedUserArgs;
import io.github.jdetmar.webflow.inputs.GetAuthorizedUserPlainArgs;
import io.github.jdetmar.webflow.inputs.GetTokenInfoArgs;
import io.github.jdetmar.webflow.inputs.GetTokenInfoPlainArgs;
import io.github.jdetmar.webflow.outputs.GetAuthorizedUserResult;
import io.github.jdetmar.webflow.outputs.GetTokenInfoResult;
import java.util.concurrent.CompletableFuture;

public final class WebflowFunctions {
    /**
     * Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user&#39;s credentials are being used. Requires the &#39;authorized_user:read&#39; scope.
     * 
     */
    public static Output<GetAuthorizedUserResult> getAuthorizedUser() {
        return getAuthorizedUser(GetAuthorizedUserArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user&#39;s credentials are being used. Requires the &#39;authorized_user:read&#39; scope.
     * 
     */
    public static CompletableFuture<GetAuthorizedUserResult> getAuthorizedUserPlain() {
        return getAuthorizedUserPlain(GetAuthorizedUserPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user&#39;s credentials are being used. Requires the &#39;authorized_user:read&#39; scope.
     * 
     */
    public static Output<GetAuthorizedUserResult> getAuthorizedUser(GetAuthorizedUserArgs args) {
        return getAuthorizedUser(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user&#39;s credentials are being used. Requires the &#39;authorized_user:read&#39; scope.
     * 
     */
    public static CompletableFuture<GetAuthorizedUserResult> getAuthorizedUserPlain(GetAuthorizedUserPlainArgs args) {
        return getAuthorizedUserPlain(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user&#39;s credentials are being used. Requires the &#39;authorized_user:read&#39; scope.
     * 
     */
    public static Output<GetAuthorizedUserResult> getAuthorizedUser(GetAuthorizedUserArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("webflow:index:getAuthorizedUser", TypeShape.of(GetAuthorizedUserResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user&#39;s credentials are being used. Requires the &#39;authorized_user:read&#39; scope.
     * 
     */
    public static Output<GetAuthorizedUserResult> getAuthorizedUser(GetAuthorizedUserArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("webflow:index:getAuthorizedUser", TypeShape.of(GetAuthorizedUserResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user&#39;s credentials are being used. Requires the &#39;authorized_user:read&#39; scope.
     * 
     */
    public static CompletableFuture<GetAuthorizedUserResult> getAuthorizedUserPlain(GetAuthorizedUserPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("webflow:index:getAuthorizedUser", TypeShape.of(GetAuthorizedUserResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves information about the current Webflow API token, including authorization details, scopes, rate limits, and the authorized resources. This is useful for validating your API token configuration and understanding what resources it can access.
     * 
     */
    public static Output<GetTokenInfoResult> getTokenInfo() {
        return getTokenInfo(GetTokenInfoArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the current Webflow API token, including authorization details, scopes, rate limits, and the authorized resources. This is useful for validating your API token configuration and understanding what resources it can access.
     * 
     */
    public static CompletableFuture<GetTokenInfoResult> getTokenInfoPlain() {
        return getTokenInfoPlain(GetTokenInfoPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the current Webflow API token, including authorization details, scopes, rate limits, and the authorized resources. This is useful for validating your API token configuration and understanding what resources it can access.
     * 
     */
    public static Output<GetTokenInfoResult> getTokenInfo(GetTokenInfoArgs args) {
        return getTokenInfo(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the current Webflow API token, including authorization details, scopes, rate limits, and the authorized resources. This is useful for validating your API token configuration and understanding what resources it can access.
     * 
     */
    public static CompletableFuture<GetTokenInfoResult> getTokenInfoPlain(GetTokenInfoPlainArgs args) {
        return getTokenInfoPlain(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves information about the current Webflow API token, including authorization details, scopes, rate limits, and the authorized resources. This is useful for validating your API token configuration and understanding what resources it can access.
     * 
     */
    public static Output<GetTokenInfoResult> getTokenInfo(GetTokenInfoArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("webflow:index:getTokenInfo", TypeShape.of(GetTokenInfoResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves information about the current Webflow API token, including authorization details, scopes, rate limits, and the authorized resources. This is useful for validating your API token configuration and understanding what resources it can access.
     * 
     */
    public static Output<GetTokenInfoResult> getTokenInfo(GetTokenInfoArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("webflow:index:getTokenInfo", TypeShape.of(GetTokenInfoResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves information about the current Webflow API token, including authorization details, scopes, rate limits, and the authorized resources. This is useful for validating your API token configuration and understanding what resources it can access.
     * 
     */
    public static CompletableFuture<GetTokenInfoResult> getTokenInfoPlain(GetTokenInfoPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("webflow:index:getTokenInfo", TypeShape.of(GetTokenInfoResult.class), args, Utilities.withVersion(options));
    }
}
