// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.webflow.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetTokenInfoAuthorizedTo {
    /**
     * @return List of site IDs this token is authorized to access.
     * 
     */
    private List<String> siteIds;
    /**
     * @return List of user IDs this token is authorized to access.
     * 
     */
    private List<String> userIds;
    /**
     * @return List of workspace IDs this token is authorized to access.
     * 
     */
    private List<String> workspaceIds;

    private GetTokenInfoAuthorizedTo() {}
    /**
     * @return List of site IDs this token is authorized to access.
     * 
     */
    public List<String> siteIds() {
        return this.siteIds;
    }
    /**
     * @return List of user IDs this token is authorized to access.
     * 
     */
    public List<String> userIds() {
        return this.userIds;
    }
    /**
     * @return List of workspace IDs this token is authorized to access.
     * 
     */
    public List<String> workspaceIds() {
        return this.workspaceIds;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTokenInfoAuthorizedTo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> siteIds;
        private List<String> userIds;
        private List<String> workspaceIds;
        public Builder() {}
        public Builder(GetTokenInfoAuthorizedTo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.siteIds = defaults.siteIds;
    	      this.userIds = defaults.userIds;
    	      this.workspaceIds = defaults.workspaceIds;
        }

        @CustomType.Setter
        public Builder siteIds(List<String> siteIds) {
            if (siteIds == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorizedTo", "siteIds");
            }
            this.siteIds = siteIds;
            return this;
        }
        public Builder siteIds(String... siteIds) {
            return siteIds(List.of(siteIds));
        }
        @CustomType.Setter
        public Builder userIds(List<String> userIds) {
            if (userIds == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorizedTo", "userIds");
            }
            this.userIds = userIds;
            return this;
        }
        public Builder userIds(String... userIds) {
            return userIds(List.of(userIds));
        }
        @CustomType.Setter
        public Builder workspaceIds(List<String> workspaceIds) {
            if (workspaceIds == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorizedTo", "workspaceIds");
            }
            this.workspaceIds = workspaceIds;
            return this;
        }
        public Builder workspaceIds(String... workspaceIds) {
            return workspaceIds(List.of(workspaceIds));
        }
        public GetTokenInfoAuthorizedTo build() {
            final var _resultValue = new GetTokenInfoAuthorizedTo();
            _resultValue.siteIds = siteIds;
            _resultValue.userIds = userIds;
            _resultValue.workspaceIds = workspaceIds;
            return _resultValue;
        }
    }
}
