// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages CMS collection items for a Webflow collection. Collection items represent individual content entries (blog posts, products, etc.) within a CMS collection. Each item has dynamic field data based on the collection schema.
type CollectionItem struct {
	pulumi.CustomResourceState

	// The locale ID for localized sites (optional, e.g., 'en-US'). Only required if your site uses Webflow's localization features. Leave empty for non-localized sites.
	CmsLocaleId pulumi.StringPtrOutput `pulumi:"cmsLocaleId"`
	// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
	CollectionId pulumi.StringOutput `pulumi:"collectionId"`
	// The timestamp when the item was created (RFC3339 format, read-only). This is automatically set by Webflow and is immutable.
	CreatedOn pulumi.StringPtrOutput `pulumi:"createdOn"`
	// A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include 'name' (required), 'slug' (required, URL-friendly), and any custom fields you've added to the collection. Example: {"name": "My Blog Post", "slug": "my-blog-post", "content": "Post content..."}
	FieldData pulumi.MapOutput `pulumi:"fieldData"`
	// Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
	IsArchived pulumi.BoolPtrOutput `pulumi:"isArchived"`
	// Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
	IsDraft pulumi.BoolPtrOutput `pulumi:"isDraft"`
	// The Webflow-assigned item ID (read-only). This is automatically set by Webflow when the item is created.
	ItemId pulumi.StringPtrOutput `pulumi:"itemId"`
	// The timestamp when the item was last published (RFC3339 format, read-only). This is automatically updated by Webflow when the item is published.
	LastPublished pulumi.StringPtrOutput `pulumi:"lastPublished"`
	// The timestamp when the item was last updated (RFC3339 format, read-only). This is automatically updated by Webflow whenever the item is modified.
	LastUpdated pulumi.StringPtrOutput `pulumi:"lastUpdated"`
}

// NewCollectionItem registers a new resource with the given unique name, arguments, and options.
func NewCollectionItem(ctx *pulumi.Context,
	name string, args *CollectionItemArgs, opts ...pulumi.ResourceOption) (*CollectionItem, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CollectionId == nil {
		return nil, errors.New("invalid value for required argument 'CollectionId'")
	}
	if args.FieldData == nil {
		return nil, errors.New("invalid value for required argument 'FieldData'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CollectionItem
	err := ctx.RegisterResource("webflow:index:CollectionItem", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCollectionItem gets an existing CollectionItem resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCollectionItem(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CollectionItemState, opts ...pulumi.ResourceOption) (*CollectionItem, error) {
	var resource CollectionItem
	err := ctx.ReadResource("webflow:index:CollectionItem", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CollectionItem resources.
type collectionItemState struct {
}

type CollectionItemState struct {
}

func (CollectionItemState) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionItemState)(nil)).Elem()
}

type collectionItemArgs struct {
	// The locale ID for localized sites (optional, e.g., 'en-US'). Only required if your site uses Webflow's localization features. Leave empty for non-localized sites.
	CmsLocaleId *string `pulumi:"cmsLocaleId"`
	// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
	CollectionId string `pulumi:"collectionId"`
	// A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include 'name' (required), 'slug' (required, URL-friendly), and any custom fields you've added to the collection. Example: {"name": "My Blog Post", "slug": "my-blog-post", "content": "Post content..."}
	FieldData map[string]interface{} `pulumi:"fieldData"`
	// Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
	IsArchived *bool `pulumi:"isArchived"`
	// Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
	IsDraft *bool `pulumi:"isDraft"`
}

// The set of arguments for constructing a CollectionItem resource.
type CollectionItemArgs struct {
	// The locale ID for localized sites (optional, e.g., 'en-US'). Only required if your site uses Webflow's localization features. Leave empty for non-localized sites.
	CmsLocaleId pulumi.StringPtrInput
	// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
	CollectionId pulumi.StringInput
	// A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include 'name' (required), 'slug' (required, URL-friendly), and any custom fields you've added to the collection. Example: {"name": "My Blog Post", "slug": "my-blog-post", "content": "Post content..."}
	FieldData pulumi.MapInput
	// Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
	IsArchived pulumi.BoolPtrInput
	// Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
	IsDraft pulumi.BoolPtrInput
}

func (CollectionItemArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionItemArgs)(nil)).Elem()
}

type CollectionItemInput interface {
	pulumi.Input

	ToCollectionItemOutput() CollectionItemOutput
	ToCollectionItemOutputWithContext(ctx context.Context) CollectionItemOutput
}

func (*CollectionItem) ElementType() reflect.Type {
	return reflect.TypeOf((**CollectionItem)(nil)).Elem()
}

func (i *CollectionItem) ToCollectionItemOutput() CollectionItemOutput {
	return i.ToCollectionItemOutputWithContext(context.Background())
}

func (i *CollectionItem) ToCollectionItemOutputWithContext(ctx context.Context) CollectionItemOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CollectionItemOutput)
}

type CollectionItemOutput struct{ *pulumi.OutputState }

func (CollectionItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CollectionItem)(nil)).Elem()
}

func (o CollectionItemOutput) ToCollectionItemOutput() CollectionItemOutput {
	return o
}

func (o CollectionItemOutput) ToCollectionItemOutputWithContext(ctx context.Context) CollectionItemOutput {
	return o
}

// The locale ID for localized sites (optional, e.g., 'en-US'). Only required if your site uses Webflow's localization features. Leave empty for non-localized sites.
func (o CollectionItemOutput) CmsLocaleId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.StringPtrOutput { return v.CmsLocaleId }).(pulumi.StringPtrOutput)
}

// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
func (o CollectionItemOutput) CollectionId() pulumi.StringOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.StringOutput { return v.CollectionId }).(pulumi.StringOutput)
}

// The timestamp when the item was created (RFC3339 format, read-only). This is automatically set by Webflow and is immutable.
func (o CollectionItemOutput) CreatedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.StringPtrOutput { return v.CreatedOn }).(pulumi.StringPtrOutput)
}

// A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include 'name' (required), 'slug' (required, URL-friendly), and any custom fields you've added to the collection. Example: {"name": "My Blog Post", "slug": "my-blog-post", "content": "Post content..."}
func (o CollectionItemOutput) FieldData() pulumi.MapOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.MapOutput { return v.FieldData }).(pulumi.MapOutput)
}

// Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
func (o CollectionItemOutput) IsArchived() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.BoolPtrOutput { return v.IsArchived }).(pulumi.BoolPtrOutput)
}

// Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
func (o CollectionItemOutput) IsDraft() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.BoolPtrOutput { return v.IsDraft }).(pulumi.BoolPtrOutput)
}

// The Webflow-assigned item ID (read-only). This is automatically set by Webflow when the item is created.
func (o CollectionItemOutput) ItemId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.StringPtrOutput { return v.ItemId }).(pulumi.StringPtrOutput)
}

// The timestamp when the item was last published (RFC3339 format, read-only). This is automatically updated by Webflow when the item is published.
func (o CollectionItemOutput) LastPublished() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.StringPtrOutput { return v.LastPublished }).(pulumi.StringPtrOutput)
}

// The timestamp when the item was last updated (RFC3339 format, read-only). This is automatically updated by Webflow whenever the item is modified.
func (o CollectionItemOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionItem) pulumi.StringPtrOutput { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CollectionItemInput)(nil)).Elem(), &CollectionItem{})
	pulumi.RegisterOutputType(CollectionItemOutput{})
}
