// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages static content (text) for a Webflow page. This resource allows you to update text content within existing DOM nodes on a page. It does NOT manage page structure or layout - only content within existing nodes. To find node IDs, you must first retrieve the page DOM structure using the Webflow API.
//
// **IMPORTANT LIMITATION:** This resource does NOT support drift detection for content changes. If content is modified outside of Pulumi (via Webflow UI or API), those changes will NOT be detected during 'pulumi refresh' or 'pulumi up'. The resource only verifies that the page still exists. This is due to the complexity of extracting and comparing specific node text from the full DOM structure.
type PageContent struct {
	pulumi.CustomResourceState

	// The timestamp when the page content was last updated (RFC3339 format). This is automatically set when content is updated and is read-only.
	LastUpdated pulumi.StringPtrOutput `pulumi:"lastUpdated"`
	// List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
	Nodes NodeContentUpdateArrayOutput `pulumi:"nodes"`
	// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
	PageId pulumi.StringOutput `pulumi:"pageId"`
}

// NewPageContent registers a new resource with the given unique name, arguments, and options.
func NewPageContent(ctx *pulumi.Context,
	name string, args *PageContentArgs, opts ...pulumi.ResourceOption) (*PageContent, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Nodes == nil {
		return nil, errors.New("invalid value for required argument 'Nodes'")
	}
	if args.PageId == nil {
		return nil, errors.New("invalid value for required argument 'PageId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PageContent
	err := ctx.RegisterResource("webflow:index:PageContent", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPageContent gets an existing PageContent resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPageContent(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PageContentState, opts ...pulumi.ResourceOption) (*PageContent, error) {
	var resource PageContent
	err := ctx.ReadResource("webflow:index:PageContent", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PageContent resources.
type pageContentState struct {
}

type PageContentState struct {
}

func (PageContentState) ElementType() reflect.Type {
	return reflect.TypeOf((*pageContentState)(nil)).Elem()
}

type pageContentArgs struct {
	// List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
	Nodes []NodeContentUpdate `pulumi:"nodes"`
	// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
	PageId string `pulumi:"pageId"`
}

// The set of arguments for constructing a PageContent resource.
type PageContentArgs struct {
	// List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
	Nodes NodeContentUpdateArrayInput
	// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
	PageId pulumi.StringInput
}

func (PageContentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pageContentArgs)(nil)).Elem()
}

type PageContentInput interface {
	pulumi.Input

	ToPageContentOutput() PageContentOutput
	ToPageContentOutputWithContext(ctx context.Context) PageContentOutput
}

func (*PageContent) ElementType() reflect.Type {
	return reflect.TypeOf((**PageContent)(nil)).Elem()
}

func (i *PageContent) ToPageContentOutput() PageContentOutput {
	return i.ToPageContentOutputWithContext(context.Background())
}

func (i *PageContent) ToPageContentOutputWithContext(ctx context.Context) PageContentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PageContentOutput)
}

type PageContentOutput struct{ *pulumi.OutputState }

func (PageContentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PageContent)(nil)).Elem()
}

func (o PageContentOutput) ToPageContentOutput() PageContentOutput {
	return o
}

func (o PageContentOutput) ToPageContentOutputWithContext(ctx context.Context) PageContentOutput {
	return o
}

// The timestamp when the page content was last updated (RFC3339 format). This is automatically set when content is updated and is read-only.
func (o PageContentOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PageContent) pulumi.StringPtrOutput { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
func (o PageContentOutput) Nodes() NodeContentUpdateArrayOutput {
	return o.ApplyT(func(v *PageContent) NodeContentUpdateArrayOutput { return v.Nodes }).(NodeContentUpdateArrayOutput)
}

// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
func (o PageContentOutput) PageId() pulumi.StringOutput {
	return o.ApplyT(func(v *PageContent) pulumi.StringOutput { return v.PageId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PageContentInput)(nil)).Elem(), &PageContent{})
	pulumi.RegisterOutputType(PageContentOutput{})
}
