// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"github.com/jdetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type PageInfo struct {
	Archived     bool    `pulumi:"archived"`
	CollectionId *string `pulumi:"collectionId"`
	CreatedOn    string  `pulumi:"createdOn"`
	Draft        bool    `pulumi:"draft"`
	LastUpdated  string  `pulumi:"lastUpdated"`
	PageId       string  `pulumi:"pageId"`
	ParentId     *string `pulumi:"parentId"`
	SiteId       string  `pulumi:"siteId"`
	Slug         string  `pulumi:"slug"`
	Title        string  `pulumi:"title"`
}

type PageInfoOutput struct{ *pulumi.OutputState }

func (PageInfoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PageInfo)(nil)).Elem()
}

func (o PageInfoOutput) ToPageInfoOutput() PageInfoOutput {
	return o
}

func (o PageInfoOutput) ToPageInfoOutputWithContext(ctx context.Context) PageInfoOutput {
	return o
}

func (o PageInfoOutput) Archived() pulumi.BoolOutput {
	return o.ApplyT(func(v PageInfo) bool { return v.Archived }).(pulumi.BoolOutput)
}

func (o PageInfoOutput) CollectionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PageInfo) *string { return v.CollectionId }).(pulumi.StringPtrOutput)
}

func (o PageInfoOutput) CreatedOn() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.CreatedOn }).(pulumi.StringOutput)
}

func (o PageInfoOutput) Draft() pulumi.BoolOutput {
	return o.ApplyT(func(v PageInfo) bool { return v.Draft }).(pulumi.BoolOutput)
}

func (o PageInfoOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o PageInfoOutput) PageId() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.PageId }).(pulumi.StringOutput)
}

func (o PageInfoOutput) ParentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PageInfo) *string { return v.ParentId }).(pulumi.StringPtrOutput)
}

func (o PageInfoOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.SiteId }).(pulumi.StringOutput)
}

func (o PageInfoOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.Slug }).(pulumi.StringOutput)
}

func (o PageInfoOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.Title }).(pulumi.StringOutput)
}

type PageInfoArrayOutput struct{ *pulumi.OutputState }

func (PageInfoArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PageInfo)(nil)).Elem()
}

func (o PageInfoArrayOutput) ToPageInfoArrayOutput() PageInfoArrayOutput {
	return o
}

func (o PageInfoArrayOutput) ToPageInfoArrayOutputWithContext(ctx context.Context) PageInfoArrayOutput {
	return o
}

func (o PageInfoArrayOutput) Index(i pulumi.IntInput) PageInfoOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PageInfo {
		return vs[0].([]PageInfo)[vs[1].(int)]
	}).(PageInfoOutput)
}

func init() {
	pulumi.RegisterOutputType(PageInfoOutput{})
	pulumi.RegisterOutputType(PageInfoArrayOutput{})
}
