// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"github.com/jdetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type CustomScriptArgs struct {
	// Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {'data-config': 'my-value'}. These attributes are passed directly to the script tag.
	Attributes map[string]interface{} `pulumi:"attributes"`
	// The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: 'cms_slider', 'analytics', 'custom_widget'
	Id string `pulumi:"id"`
	// The location where the script is placed on the page. Valid values: 'header' (placed in the <head> section), 'footer' (placed before </body>). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
	Location string `pulumi:"location"`
	// The semantic version string for the registered script (e.g., '1.0.0', '0.1.2'). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
	Version string `pulumi:"version"`
}

// CustomScriptArgsInput is an input type that accepts CustomScriptArgsArgs and CustomScriptArgsOutput values.
// You can construct a concrete instance of `CustomScriptArgsInput` via:
//
//	CustomScriptArgsArgs{...}
type CustomScriptArgsInput interface {
	pulumi.Input

	ToCustomScriptArgsOutput() CustomScriptArgsOutput
	ToCustomScriptArgsOutputWithContext(context.Context) CustomScriptArgsOutput
}

type CustomScriptArgsArgs struct {
	// Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {'data-config': 'my-value'}. These attributes are passed directly to the script tag.
	Attributes pulumi.MapInput `pulumi:"attributes"`
	// The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: 'cms_slider', 'analytics', 'custom_widget'
	Id pulumi.StringInput `pulumi:"id"`
	// The location where the script is placed on the page. Valid values: 'header' (placed in the <head> section), 'footer' (placed before </body>). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
	Location pulumi.StringInput `pulumi:"location"`
	// The semantic version string for the registered script (e.g., '1.0.0', '0.1.2'). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
	Version pulumi.StringInput `pulumi:"version"`
}

func (CustomScriptArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CustomScriptArgs)(nil)).Elem()
}

func (i CustomScriptArgsArgs) ToCustomScriptArgsOutput() CustomScriptArgsOutput {
	return i.ToCustomScriptArgsOutputWithContext(context.Background())
}

func (i CustomScriptArgsArgs) ToCustomScriptArgsOutputWithContext(ctx context.Context) CustomScriptArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomScriptArgsOutput)
}

// CustomScriptArgsArrayInput is an input type that accepts CustomScriptArgsArray and CustomScriptArgsArrayOutput values.
// You can construct a concrete instance of `CustomScriptArgsArrayInput` via:
//
//	CustomScriptArgsArray{ CustomScriptArgsArgs{...} }
type CustomScriptArgsArrayInput interface {
	pulumi.Input

	ToCustomScriptArgsArrayOutput() CustomScriptArgsArrayOutput
	ToCustomScriptArgsArrayOutputWithContext(context.Context) CustomScriptArgsArrayOutput
}

type CustomScriptArgsArray []CustomScriptArgsInput

func (CustomScriptArgsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]CustomScriptArgs)(nil)).Elem()
}

func (i CustomScriptArgsArray) ToCustomScriptArgsArrayOutput() CustomScriptArgsArrayOutput {
	return i.ToCustomScriptArgsArrayOutputWithContext(context.Background())
}

func (i CustomScriptArgsArray) ToCustomScriptArgsArrayOutputWithContext(ctx context.Context) CustomScriptArgsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomScriptArgsArrayOutput)
}

type CustomScriptArgsOutput struct{ *pulumi.OutputState }

func (CustomScriptArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CustomScriptArgs)(nil)).Elem()
}

func (o CustomScriptArgsOutput) ToCustomScriptArgsOutput() CustomScriptArgsOutput {
	return o
}

func (o CustomScriptArgsOutput) ToCustomScriptArgsOutputWithContext(ctx context.Context) CustomScriptArgsOutput {
	return o
}

// Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {'data-config': 'my-value'}. These attributes are passed directly to the script tag.
func (o CustomScriptArgsOutput) Attributes() pulumi.MapOutput {
	return o.ApplyT(func(v CustomScriptArgs) map[string]interface{} { return v.Attributes }).(pulumi.MapOutput)
}

// The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: 'cms_slider', 'analytics', 'custom_widget'
func (o CustomScriptArgsOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v CustomScriptArgs) string { return v.Id }).(pulumi.StringOutput)
}

// The location where the script is placed on the page. Valid values: 'header' (placed in the <head> section), 'footer' (placed before </body>). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
func (o CustomScriptArgsOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v CustomScriptArgs) string { return v.Location }).(pulumi.StringOutput)
}

// The semantic version string for the registered script (e.g., '1.0.0', '0.1.2'). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
func (o CustomScriptArgsOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v CustomScriptArgs) string { return v.Version }).(pulumi.StringOutput)
}

type CustomScriptArgsArrayOutput struct{ *pulumi.OutputState }

func (CustomScriptArgsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]CustomScriptArgs)(nil)).Elem()
}

func (o CustomScriptArgsArrayOutput) ToCustomScriptArgsArrayOutput() CustomScriptArgsArrayOutput {
	return o
}

func (o CustomScriptArgsArrayOutput) ToCustomScriptArgsArrayOutputWithContext(ctx context.Context) CustomScriptArgsArrayOutput {
	return o
}

func (o CustomScriptArgsArrayOutput) Index(i pulumi.IntInput) CustomScriptArgsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) CustomScriptArgs {
		return vs[0].([]CustomScriptArgs)[vs[1].(int)]
	}).(CustomScriptArgsOutput)
}

type GetTokenInfoApplication struct {
	// The application description.
	Description string `pulumi:"description"`
	// The human-readable name of the application.
	DisplayName string `pulumi:"displayName"`
	// The application homepage URL.
	Homepage string `pulumi:"homepage"`
	// The unique identifier for the application.
	Id string `pulumi:"id"`
}

type GetTokenInfoApplicationOutput struct{ *pulumi.OutputState }

func (GetTokenInfoApplicationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokenInfoApplication)(nil)).Elem()
}

func (o GetTokenInfoApplicationOutput) ToGetTokenInfoApplicationOutput() GetTokenInfoApplicationOutput {
	return o
}

func (o GetTokenInfoApplicationOutput) ToGetTokenInfoApplicationOutputWithContext(ctx context.Context) GetTokenInfoApplicationOutput {
	return o
}

// The application description.
func (o GetTokenInfoApplicationOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoApplication) string { return v.Description }).(pulumi.StringOutput)
}

// The human-readable name of the application.
func (o GetTokenInfoApplicationOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoApplication) string { return v.DisplayName }).(pulumi.StringOutput)
}

// The application homepage URL.
func (o GetTokenInfoApplicationOutput) Homepage() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoApplication) string { return v.Homepage }).(pulumi.StringOutput)
}

// The unique identifier for the application.
func (o GetTokenInfoApplicationOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoApplication) string { return v.Id }).(pulumi.StringOutput)
}

type GetTokenInfoAuthorization struct {
	// The resources this token is authorized to access.
	AuthorizedTo GetTokenInfoAuthorizedTo `pulumi:"authorizedTo"`
	// The timestamp when this authorization was created (RFC3339 format).
	CreatedOn string `pulumi:"createdOn"`
	// The OAuth grant type used to obtain this token (e.g., 'authorization_code').
	GrantType string `pulumi:"grantType"`
	// The unique identifier for this authorization.
	Id string `pulumi:"id"`
	// The timestamp when this token was last used (RFC3339 format).
	LastUsed string `pulumi:"lastUsed"`
	// The rate limit for this token in requests per minute.
	RateLimit int `pulumi:"rateLimit"`
	// The OAuth scopes granted to this token (space or comma separated).
	Scope string `pulumi:"scope"`
}

type GetTokenInfoAuthorizationOutput struct{ *pulumi.OutputState }

func (GetTokenInfoAuthorizationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokenInfoAuthorization)(nil)).Elem()
}

func (o GetTokenInfoAuthorizationOutput) ToGetTokenInfoAuthorizationOutput() GetTokenInfoAuthorizationOutput {
	return o
}

func (o GetTokenInfoAuthorizationOutput) ToGetTokenInfoAuthorizationOutputWithContext(ctx context.Context) GetTokenInfoAuthorizationOutput {
	return o
}

// The resources this token is authorized to access.
func (o GetTokenInfoAuthorizationOutput) AuthorizedTo() GetTokenInfoAuthorizedToOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorization) GetTokenInfoAuthorizedTo { return v.AuthorizedTo }).(GetTokenInfoAuthorizedToOutput)
}

// The timestamp when this authorization was created (RFC3339 format).
func (o GetTokenInfoAuthorizationOutput) CreatedOn() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorization) string { return v.CreatedOn }).(pulumi.StringOutput)
}

// The OAuth grant type used to obtain this token (e.g., 'authorization_code').
func (o GetTokenInfoAuthorizationOutput) GrantType() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorization) string { return v.GrantType }).(pulumi.StringOutput)
}

// The unique identifier for this authorization.
func (o GetTokenInfoAuthorizationOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorization) string { return v.Id }).(pulumi.StringOutput)
}

// The timestamp when this token was last used (RFC3339 format).
func (o GetTokenInfoAuthorizationOutput) LastUsed() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorization) string { return v.LastUsed }).(pulumi.StringOutput)
}

// The rate limit for this token in requests per minute.
func (o GetTokenInfoAuthorizationOutput) RateLimit() pulumi.IntOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorization) int { return v.RateLimit }).(pulumi.IntOutput)
}

// The OAuth scopes granted to this token (space or comma separated).
func (o GetTokenInfoAuthorizationOutput) Scope() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorization) string { return v.Scope }).(pulumi.StringOutput)
}

type GetTokenInfoAuthorizedTo struct {
	// List of site IDs this token is authorized to access.
	SiteIds []string `pulumi:"siteIds"`
	// List of user IDs this token is authorized to access.
	UserIds []string `pulumi:"userIds"`
	// List of workspace IDs this token is authorized to access.
	WorkspaceIds []string `pulumi:"workspaceIds"`
}

type GetTokenInfoAuthorizedToOutput struct{ *pulumi.OutputState }

func (GetTokenInfoAuthorizedToOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokenInfoAuthorizedTo)(nil)).Elem()
}

func (o GetTokenInfoAuthorizedToOutput) ToGetTokenInfoAuthorizedToOutput() GetTokenInfoAuthorizedToOutput {
	return o
}

func (o GetTokenInfoAuthorizedToOutput) ToGetTokenInfoAuthorizedToOutputWithContext(ctx context.Context) GetTokenInfoAuthorizedToOutput {
	return o
}

// List of site IDs this token is authorized to access.
func (o GetTokenInfoAuthorizedToOutput) SiteIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorizedTo) []string { return v.SiteIds }).(pulumi.StringArrayOutput)
}

// List of user IDs this token is authorized to access.
func (o GetTokenInfoAuthorizedToOutput) UserIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorizedTo) []string { return v.UserIds }).(pulumi.StringArrayOutput)
}

// List of workspace IDs this token is authorized to access.
func (o GetTokenInfoAuthorizedToOutput) WorkspaceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTokenInfoAuthorizedTo) []string { return v.WorkspaceIds }).(pulumi.StringArrayOutput)
}

type NodeContentUpdate struct {
	// The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
	NodeId string `pulumi:"nodeId"`
	// The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
	Text string `pulumi:"text"`
}

// NodeContentUpdateInput is an input type that accepts NodeContentUpdateArgs and NodeContentUpdateOutput values.
// You can construct a concrete instance of `NodeContentUpdateInput` via:
//
//	NodeContentUpdateArgs{...}
type NodeContentUpdateInput interface {
	pulumi.Input

	ToNodeContentUpdateOutput() NodeContentUpdateOutput
	ToNodeContentUpdateOutputWithContext(context.Context) NodeContentUpdateOutput
}

type NodeContentUpdateArgs struct {
	// The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
	NodeId pulumi.StringInput `pulumi:"nodeId"`
	// The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
	Text pulumi.StringInput `pulumi:"text"`
}

func (NodeContentUpdateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NodeContentUpdate)(nil)).Elem()
}

func (i NodeContentUpdateArgs) ToNodeContentUpdateOutput() NodeContentUpdateOutput {
	return i.ToNodeContentUpdateOutputWithContext(context.Background())
}

func (i NodeContentUpdateArgs) ToNodeContentUpdateOutputWithContext(ctx context.Context) NodeContentUpdateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodeContentUpdateOutput)
}

// NodeContentUpdateArrayInput is an input type that accepts NodeContentUpdateArray and NodeContentUpdateArrayOutput values.
// You can construct a concrete instance of `NodeContentUpdateArrayInput` via:
//
//	NodeContentUpdateArray{ NodeContentUpdateArgs{...} }
type NodeContentUpdateArrayInput interface {
	pulumi.Input

	ToNodeContentUpdateArrayOutput() NodeContentUpdateArrayOutput
	ToNodeContentUpdateArrayOutputWithContext(context.Context) NodeContentUpdateArrayOutput
}

type NodeContentUpdateArray []NodeContentUpdateInput

func (NodeContentUpdateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NodeContentUpdate)(nil)).Elem()
}

func (i NodeContentUpdateArray) ToNodeContentUpdateArrayOutput() NodeContentUpdateArrayOutput {
	return i.ToNodeContentUpdateArrayOutputWithContext(context.Background())
}

func (i NodeContentUpdateArray) ToNodeContentUpdateArrayOutputWithContext(ctx context.Context) NodeContentUpdateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodeContentUpdateArrayOutput)
}

type NodeContentUpdateOutput struct{ *pulumi.OutputState }

func (NodeContentUpdateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NodeContentUpdate)(nil)).Elem()
}

func (o NodeContentUpdateOutput) ToNodeContentUpdateOutput() NodeContentUpdateOutput {
	return o
}

func (o NodeContentUpdateOutput) ToNodeContentUpdateOutputWithContext(ctx context.Context) NodeContentUpdateOutput {
	return o
}

// The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
func (o NodeContentUpdateOutput) NodeId() pulumi.StringOutput {
	return o.ApplyT(func(v NodeContentUpdate) string { return v.NodeId }).(pulumi.StringOutput)
}

// The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
func (o NodeContentUpdateOutput) Text() pulumi.StringOutput {
	return o.ApplyT(func(v NodeContentUpdate) string { return v.Text }).(pulumi.StringOutput)
}

type NodeContentUpdateArrayOutput struct{ *pulumi.OutputState }

func (NodeContentUpdateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NodeContentUpdate)(nil)).Elem()
}

func (o NodeContentUpdateArrayOutput) ToNodeContentUpdateArrayOutput() NodeContentUpdateArrayOutput {
	return o
}

func (o NodeContentUpdateArrayOutput) ToNodeContentUpdateArrayOutputWithContext(ctx context.Context) NodeContentUpdateArrayOutput {
	return o
}

func (o NodeContentUpdateArrayOutput) Index(i pulumi.IntInput) NodeContentUpdateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NodeContentUpdate {
		return vs[0].([]NodeContentUpdate)[vs[1].(int)]
	}).(NodeContentUpdateOutput)
}

type PageCustomCodeScript struct {
	// Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
	Attributes map[string]interface{} `pulumi:"attributes"`
	// The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
	Id string `pulumi:"id"`
	// Where the script should be applied on the page. Must be either 'header' (loaded in page header) or 'footer' (loaded at end of page). Use 'header' for scripts that don't depend on DOM elements. Use 'footer' for scripts that need to run after DOM is fully loaded.
	Location string `pulumi:"location"`
	// The semantic version string for the registered script (e.g., '1.0.0'). This version must match a registered version of the script. You can have multiple versions of the same script registered.
	Version string `pulumi:"version"`
}

// PageCustomCodeScriptInput is an input type that accepts PageCustomCodeScriptArgs and PageCustomCodeScriptOutput values.
// You can construct a concrete instance of `PageCustomCodeScriptInput` via:
//
//	PageCustomCodeScriptArgs{...}
type PageCustomCodeScriptInput interface {
	pulumi.Input

	ToPageCustomCodeScriptOutput() PageCustomCodeScriptOutput
	ToPageCustomCodeScriptOutputWithContext(context.Context) PageCustomCodeScriptOutput
}

type PageCustomCodeScriptArgs struct {
	// Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
	Attributes pulumi.MapInput `pulumi:"attributes"`
	// The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
	Id pulumi.StringInput `pulumi:"id"`
	// Where the script should be applied on the page. Must be either 'header' (loaded in page header) or 'footer' (loaded at end of page). Use 'header' for scripts that don't depend on DOM elements. Use 'footer' for scripts that need to run after DOM is fully loaded.
	Location pulumi.StringInput `pulumi:"location"`
	// The semantic version string for the registered script (e.g., '1.0.0'). This version must match a registered version of the script. You can have multiple versions of the same script registered.
	Version pulumi.StringInput `pulumi:"version"`
}

func (PageCustomCodeScriptArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PageCustomCodeScript)(nil)).Elem()
}

func (i PageCustomCodeScriptArgs) ToPageCustomCodeScriptOutput() PageCustomCodeScriptOutput {
	return i.ToPageCustomCodeScriptOutputWithContext(context.Background())
}

func (i PageCustomCodeScriptArgs) ToPageCustomCodeScriptOutputWithContext(ctx context.Context) PageCustomCodeScriptOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PageCustomCodeScriptOutput)
}

// PageCustomCodeScriptArrayInput is an input type that accepts PageCustomCodeScriptArray and PageCustomCodeScriptArrayOutput values.
// You can construct a concrete instance of `PageCustomCodeScriptArrayInput` via:
//
//	PageCustomCodeScriptArray{ PageCustomCodeScriptArgs{...} }
type PageCustomCodeScriptArrayInput interface {
	pulumi.Input

	ToPageCustomCodeScriptArrayOutput() PageCustomCodeScriptArrayOutput
	ToPageCustomCodeScriptArrayOutputWithContext(context.Context) PageCustomCodeScriptArrayOutput
}

type PageCustomCodeScriptArray []PageCustomCodeScriptInput

func (PageCustomCodeScriptArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PageCustomCodeScript)(nil)).Elem()
}

func (i PageCustomCodeScriptArray) ToPageCustomCodeScriptArrayOutput() PageCustomCodeScriptArrayOutput {
	return i.ToPageCustomCodeScriptArrayOutputWithContext(context.Background())
}

func (i PageCustomCodeScriptArray) ToPageCustomCodeScriptArrayOutputWithContext(ctx context.Context) PageCustomCodeScriptArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PageCustomCodeScriptArrayOutput)
}

type PageCustomCodeScriptOutput struct{ *pulumi.OutputState }

func (PageCustomCodeScriptOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PageCustomCodeScript)(nil)).Elem()
}

func (o PageCustomCodeScriptOutput) ToPageCustomCodeScriptOutput() PageCustomCodeScriptOutput {
	return o
}

func (o PageCustomCodeScriptOutput) ToPageCustomCodeScriptOutputWithContext(ctx context.Context) PageCustomCodeScriptOutput {
	return o
}

// Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
func (o PageCustomCodeScriptOutput) Attributes() pulumi.MapOutput {
	return o.ApplyT(func(v PageCustomCodeScript) map[string]interface{} { return v.Attributes }).(pulumi.MapOutput)
}

// The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
func (o PageCustomCodeScriptOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v PageCustomCodeScript) string { return v.Id }).(pulumi.StringOutput)
}

// Where the script should be applied on the page. Must be either 'header' (loaded in page header) or 'footer' (loaded at end of page). Use 'header' for scripts that don't depend on DOM elements. Use 'footer' for scripts that need to run after DOM is fully loaded.
func (o PageCustomCodeScriptOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v PageCustomCodeScript) string { return v.Location }).(pulumi.StringOutput)
}

// The semantic version string for the registered script (e.g., '1.0.0'). This version must match a registered version of the script. You can have multiple versions of the same script registered.
func (o PageCustomCodeScriptOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v PageCustomCodeScript) string { return v.Version }).(pulumi.StringOutput)
}

type PageCustomCodeScriptArrayOutput struct{ *pulumi.OutputState }

func (PageCustomCodeScriptArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PageCustomCodeScript)(nil)).Elem()
}

func (o PageCustomCodeScriptArrayOutput) ToPageCustomCodeScriptArrayOutput() PageCustomCodeScriptArrayOutput {
	return o
}

func (o PageCustomCodeScriptArrayOutput) ToPageCustomCodeScriptArrayOutputWithContext(ctx context.Context) PageCustomCodeScriptArrayOutput {
	return o
}

func (o PageCustomCodeScriptArrayOutput) Index(i pulumi.IntInput) PageCustomCodeScriptOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PageCustomCodeScript {
		return vs[0].([]PageCustomCodeScript)[vs[1].(int)]
	}).(PageCustomCodeScriptOutput)
}

type PageInfo struct {
	Archived     bool    `pulumi:"archived"`
	CollectionId *string `pulumi:"collectionId"`
	CreatedOn    string  `pulumi:"createdOn"`
	Draft        bool    `pulumi:"draft"`
	LastUpdated  string  `pulumi:"lastUpdated"`
	PageId       string  `pulumi:"pageId"`
	ParentId     *string `pulumi:"parentId"`
	SiteId       string  `pulumi:"siteId"`
	Slug         string  `pulumi:"slug"`
	Title        string  `pulumi:"title"`
}

type PageInfoOutput struct{ *pulumi.OutputState }

func (PageInfoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PageInfo)(nil)).Elem()
}

func (o PageInfoOutput) ToPageInfoOutput() PageInfoOutput {
	return o
}

func (o PageInfoOutput) ToPageInfoOutputWithContext(ctx context.Context) PageInfoOutput {
	return o
}

func (o PageInfoOutput) Archived() pulumi.BoolOutput {
	return o.ApplyT(func(v PageInfo) bool { return v.Archived }).(pulumi.BoolOutput)
}

func (o PageInfoOutput) CollectionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PageInfo) *string { return v.CollectionId }).(pulumi.StringPtrOutput)
}

func (o PageInfoOutput) CreatedOn() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.CreatedOn }).(pulumi.StringOutput)
}

func (o PageInfoOutput) Draft() pulumi.BoolOutput {
	return o.ApplyT(func(v PageInfo) bool { return v.Draft }).(pulumi.BoolOutput)
}

func (o PageInfoOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o PageInfoOutput) PageId() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.PageId }).(pulumi.StringOutput)
}

func (o PageInfoOutput) ParentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PageInfo) *string { return v.ParentId }).(pulumi.StringPtrOutput)
}

func (o PageInfoOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.SiteId }).(pulumi.StringOutput)
}

func (o PageInfoOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.Slug }).(pulumi.StringOutput)
}

func (o PageInfoOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v PageInfo) string { return v.Title }).(pulumi.StringOutput)
}

type PageInfoArrayOutput struct{ *pulumi.OutputState }

func (PageInfoArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PageInfo)(nil)).Elem()
}

func (o PageInfoArrayOutput) ToPageInfoArrayOutput() PageInfoArrayOutput {
	return o
}

func (o PageInfoArrayOutput) ToPageInfoArrayOutputWithContext(ctx context.Context) PageInfoArrayOutput {
	return o
}

func (o PageInfoArrayOutput) Index(i pulumi.IntInput) PageInfoOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PageInfo {
		return vs[0].([]PageInfo)[vs[1].(int)]
	}).(PageInfoOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CustomScriptArgsInput)(nil)).Elem(), CustomScriptArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomScriptArgsArrayInput)(nil)).Elem(), CustomScriptArgsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodeContentUpdateInput)(nil)).Elem(), NodeContentUpdateArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodeContentUpdateArrayInput)(nil)).Elem(), NodeContentUpdateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PageCustomCodeScriptInput)(nil)).Elem(), PageCustomCodeScriptArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PageCustomCodeScriptArrayInput)(nil)).Elem(), PageCustomCodeScriptArray{})
	pulumi.RegisterOutputType(CustomScriptArgsOutput{})
	pulumi.RegisterOutputType(CustomScriptArgsArrayOutput{})
	pulumi.RegisterOutputType(GetTokenInfoApplicationOutput{})
	pulumi.RegisterOutputType(GetTokenInfoAuthorizationOutput{})
	pulumi.RegisterOutputType(GetTokenInfoAuthorizedToOutput{})
	pulumi.RegisterOutputType(NodeContentUpdateOutput{})
	pulumi.RegisterOutputType(NodeContentUpdateArrayOutput{})
	pulumi.RegisterOutputType(PageCustomCodeScriptOutput{})
	pulumi.RegisterOutputType(PageCustomCodeScriptArrayOutput{})
	pulumi.RegisterOutputType(PageInfoOutput{})
	pulumi.RegisterOutputType(PageInfoArrayOutput{})
}
