// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/jdetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages HTTP redirects for a Webflow site. This resource allows you to define redirect rules for old URLs to new locations, supporting both permanent (301) and temporary (302) redirects.
type Redirect struct {
	pulumi.CustomResourceState

	// The timestamp when the redirect was created (RFC3339 format). This is automatically set when the redirect is created and is read-only.
	CreatedOn pulumi.StringPtrOutput `pulumi:"createdOn"`
	// The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path.
	DestinationPath pulumi.StringOutput `pulumi:"destinationPath"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls (siteId validation is performed during CRUD operations in Story 2.2).
	SiteId pulumi.StringOutput `pulumi:"siteId"`
	// The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path.
	SourcePath pulumi.StringOutput `pulumi:"sourcePath"`
	// The HTTP status code for the redirect. Must be either 301 or 302. 301 = permanent redirect (use when a page has moved permanently; search engines update their index). 302 = temporary redirect (use for maintenance or temporary page moves).
	StatusCode pulumi.IntOutput `pulumi:"statusCode"`
}

// NewRedirect registers a new resource with the given unique name, arguments, and options.
func NewRedirect(ctx *pulumi.Context,
	name string, args *RedirectArgs, opts ...pulumi.ResourceOption) (*Redirect, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DestinationPath == nil {
		return nil, errors.New("invalid value for required argument 'DestinationPath'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	if args.SourcePath == nil {
		return nil, errors.New("invalid value for required argument 'SourcePath'")
	}
	if args.StatusCode == nil {
		return nil, errors.New("invalid value for required argument 'StatusCode'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Redirect
	err := ctx.RegisterResource("webflow:index:Redirect", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRedirect gets an existing Redirect resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRedirect(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RedirectState, opts ...pulumi.ResourceOption) (*Redirect, error) {
	var resource Redirect
	err := ctx.ReadResource("webflow:index:Redirect", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Redirect resources.
type redirectState struct {
}

type RedirectState struct {
}

func (RedirectState) ElementType() reflect.Type {
	return reflect.TypeOf((*redirectState)(nil)).Elem()
}

type redirectArgs struct {
	// The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path.
	DestinationPath string `pulumi:"destinationPath"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls (siteId validation is performed during CRUD operations in Story 2.2).
	SiteId string `pulumi:"siteId"`
	// The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path.
	SourcePath string `pulumi:"sourcePath"`
	// The HTTP status code for the redirect. Must be either 301 or 302. 301 = permanent redirect (use when a page has moved permanently; search engines update their index). 302 = temporary redirect (use for maintenance or temporary page moves).
	StatusCode int `pulumi:"statusCode"`
}

// The set of arguments for constructing a Redirect resource.
type RedirectArgs struct {
	// The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path.
	DestinationPath pulumi.StringInput
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls (siteId validation is performed during CRUD operations in Story 2.2).
	SiteId pulumi.StringInput
	// The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path.
	SourcePath pulumi.StringInput
	// The HTTP status code for the redirect. Must be either 301 or 302. 301 = permanent redirect (use when a page has moved permanently; search engines update their index). 302 = temporary redirect (use for maintenance or temporary page moves).
	StatusCode pulumi.IntInput
}

func (RedirectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*redirectArgs)(nil)).Elem()
}

type RedirectInput interface {
	pulumi.Input

	ToRedirectOutput() RedirectOutput
	ToRedirectOutputWithContext(ctx context.Context) RedirectOutput
}

func (*Redirect) ElementType() reflect.Type {
	return reflect.TypeOf((**Redirect)(nil)).Elem()
}

func (i *Redirect) ToRedirectOutput() RedirectOutput {
	return i.ToRedirectOutputWithContext(context.Background())
}

func (i *Redirect) ToRedirectOutputWithContext(ctx context.Context) RedirectOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RedirectOutput)
}

// RedirectArrayInput is an input type that accepts RedirectArray and RedirectArrayOutput values.
// You can construct a concrete instance of `RedirectArrayInput` via:
//
//	RedirectArray{ RedirectArgs{...} }
type RedirectArrayInput interface {
	pulumi.Input

	ToRedirectArrayOutput() RedirectArrayOutput
	ToRedirectArrayOutputWithContext(context.Context) RedirectArrayOutput
}

type RedirectArray []RedirectInput

func (RedirectArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Redirect)(nil)).Elem()
}

func (i RedirectArray) ToRedirectArrayOutput() RedirectArrayOutput {
	return i.ToRedirectArrayOutputWithContext(context.Background())
}

func (i RedirectArray) ToRedirectArrayOutputWithContext(ctx context.Context) RedirectArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RedirectArrayOutput)
}

// RedirectMapInput is an input type that accepts RedirectMap and RedirectMapOutput values.
// You can construct a concrete instance of `RedirectMapInput` via:
//
//	RedirectMap{ "key": RedirectArgs{...} }
type RedirectMapInput interface {
	pulumi.Input

	ToRedirectMapOutput() RedirectMapOutput
	ToRedirectMapOutputWithContext(context.Context) RedirectMapOutput
}

type RedirectMap map[string]RedirectInput

func (RedirectMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Redirect)(nil)).Elem()
}

func (i RedirectMap) ToRedirectMapOutput() RedirectMapOutput {
	return i.ToRedirectMapOutputWithContext(context.Background())
}

func (i RedirectMap) ToRedirectMapOutputWithContext(ctx context.Context) RedirectMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RedirectMapOutput)
}

type RedirectOutput struct{ *pulumi.OutputState }

func (RedirectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Redirect)(nil)).Elem()
}

func (o RedirectOutput) ToRedirectOutput() RedirectOutput {
	return o
}

func (o RedirectOutput) ToRedirectOutputWithContext(ctx context.Context) RedirectOutput {
	return o
}

// The timestamp when the redirect was created (RFC3339 format). This is automatically set when the redirect is created and is read-only.
func (o RedirectOutput) CreatedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Redirect) pulumi.StringPtrOutput { return v.CreatedOn }).(pulumi.StringPtrOutput)
}

// The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path.
func (o RedirectOutput) DestinationPath() pulumi.StringOutput {
	return o.ApplyT(func(v *Redirect) pulumi.StringOutput { return v.DestinationPath }).(pulumi.StringOutput)
}

// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls (siteId validation is performed during CRUD operations in Story 2.2).
func (o RedirectOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *Redirect) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

// The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path.
func (o RedirectOutput) SourcePath() pulumi.StringOutput {
	return o.ApplyT(func(v *Redirect) pulumi.StringOutput { return v.SourcePath }).(pulumi.StringOutput)
}

// The HTTP status code for the redirect. Must be either 301 or 302. 301 = permanent redirect (use when a page has moved permanently; search engines update their index). 302 = temporary redirect (use for maintenance or temporary page moves).
func (o RedirectOutput) StatusCode() pulumi.IntOutput {
	return o.ApplyT(func(v *Redirect) pulumi.IntOutput { return v.StatusCode }).(pulumi.IntOutput)
}

type RedirectArrayOutput struct{ *pulumi.OutputState }

func (RedirectArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Redirect)(nil)).Elem()
}

func (o RedirectArrayOutput) ToRedirectArrayOutput() RedirectArrayOutput {
	return o
}

func (o RedirectArrayOutput) ToRedirectArrayOutputWithContext(ctx context.Context) RedirectArrayOutput {
	return o
}

func (o RedirectArrayOutput) Index(i pulumi.IntInput) RedirectOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Redirect {
		return vs[0].([]*Redirect)[vs[1].(int)]
	}).(RedirectOutput)
}

type RedirectMapOutput struct{ *pulumi.OutputState }

func (RedirectMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Redirect)(nil)).Elem()
}

func (o RedirectMapOutput) ToRedirectMapOutput() RedirectMapOutput {
	return o
}

func (o RedirectMapOutput) ToRedirectMapOutputWithContext(ctx context.Context) RedirectMapOutput {
	return o
}

func (o RedirectMapOutput) MapIndex(k pulumi.StringInput) RedirectOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Redirect {
		return vs[0].(map[string]*Redirect)[vs[1].(string)]
	}).(RedirectOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RedirectInput)(nil)).Elem(), &Redirect{})
	pulumi.RegisterInputType(reflect.TypeOf((*RedirectArrayInput)(nil)).Elem(), RedirectArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RedirectMapInput)(nil)).Elem(), RedirectMap{})
	pulumi.RegisterOutputType(RedirectOutput{})
	pulumi.RegisterOutputType(RedirectArrayOutput{})
	pulumi.RegisterOutputType(RedirectMapOutput{})
}
