// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/jdetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages Webflow sites programmatically. This resource allows you to create, configure, and manage Webflow sites through infrastructure code. Create, Read, Update, and Delete operations are fully supported for complete site lifecycle management.
type Site struct {
	pulumi.CustomResourceState

	// List of custom domains attached to the site (read-only in this release). Custom domain management will be available in a future release.
	CustomDomains pulumi.StringArrayOutput `pulumi:"customDomains"`
	// Indicates whether data collection is enabled for this site (read-only). Controlled by your Webflow workspace settings, not per-site.
	DataCollectionEnabled pulumi.BoolPtrOutput `pulumi:"dataCollectionEnabled"`
	// The type of data collection enabled for the site (read-only). Possible values: 'always' (always collect), 'optOut' (collect by default), 'disabled' (no collection). Controlled by your Webflow workspace settings, not per-site.
	DataCollectionType pulumi.StringPtrOutput `pulumi:"dataCollectionType"`
	// The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// The RFC3339 timestamp of the last time the site was published (read-only). Automatically set by Webflow when changes are published to production.
	LastPublished pulumi.StringPtrOutput `pulumi:"lastPublished"`
	// The RFC3339 timestamp of the last time the site configuration was updated (read-only). Automatically set by Webflow when any site changes occur.
	LastUpdated pulumi.StringPtrOutput `pulumi:"lastUpdated"`
	// The folder ID where the site will be organized in the Webflow dashboard. Optional - the site will be placed at the workspace root if not specified. This is useful for organizing multiple sites into logical groups within your workspace.
	ParentFolderId pulumi.StringPtrOutput `pulumi:"parentFolderId"`
	// The URL to a preview image of the site (read-only). Automatically generated by Webflow for site thumbnails in the dashboard.
	PreviewUrl pulumi.StringPtrOutput `pulumi:"previewUrl"`
	// Automatically publish the site after creation or updates. When set to true, the provider will publish the site to production after successfully creating or updating it. Default: false (manual publishing required). Note: Site must have at least one published version before automatic publishing will work. If publishing fails, the entire operation will fail with an error (site may exist but Pulumi will report failure). Recommendation: Set to false for initial site creation, then enable after first manual publish.
	Publish pulumi.BoolPtrOutput `pulumi:"publish"`
	// The slugified version of the site name used in URLs and for file organization. Optional - if not provided, Webflow will automatically generate one from the displayName. Must use only lowercase letters (a-z), numbers (0-9), and hyphens (-). No spaces, underscores, or special characters allowed. Must start and end with a letter or number (no leading/trailing hyphens). Examples: 'my-site', 'company-blog-2024', 'product-landing-page'.
	ShortName pulumi.StringPtrOutput `pulumi:"shortName"`
	// The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **WARNING: This field is IMMUTABLE.** Once set, it cannot be changed. Changing this value will trigger a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
	TemplateName pulumi.StringPtrOutput `pulumi:"templateName"`
	// The IANA timezone identifier for the site. Optional - Webflow will use its default timezone if not specified. Use standard IANA timezone identifiers (e.g., 'America/New_York', 'Europe/London', 'Asia/Tokyo', 'UTC'). This timezone is used for scheduling, analytics, and other time-sensitive features.
	TimeZone pulumi.StringPtrOutput `pulumi:"timeZone"`
	// The Webflow workspace ID where the site will be created. Required for site creation (Enterprise workspace required by Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace.
	WorkspaceId pulumi.StringOutput `pulumi:"workspaceId"`
}

// NewSite registers a new resource with the given unique name, arguments, and options.
func NewSite(ctx *pulumi.Context,
	name string, args *SiteArgs, opts ...pulumi.ResourceOption) (*Site, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	if args.WorkspaceId == nil {
		return nil, errors.New("invalid value for required argument 'WorkspaceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Site
	err := ctx.RegisterResource("webflow:index:Site", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSite gets an existing Site resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSite(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SiteState, opts ...pulumi.ResourceOption) (*Site, error) {
	var resource Site
	err := ctx.ReadResource("webflow:index:Site", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Site resources.
type siteState struct {
}

type SiteState struct {
}

func (SiteState) ElementType() reflect.Type {
	return reflect.TypeOf((*siteState)(nil)).Elem()
}

type siteArgs struct {
	// The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
	DisplayName string `pulumi:"displayName"`
	// The folder ID where the site will be organized in the Webflow dashboard. Optional - the site will be placed at the workspace root if not specified. This is useful for organizing multiple sites into logical groups within your workspace.
	ParentFolderId *string `pulumi:"parentFolderId"`
	// Automatically publish the site after creation or updates. When set to true, the provider will publish the site to production after successfully creating or updating it. Default: false (manual publishing required). Note: Site must have at least one published version before automatic publishing will work. If publishing fails, the entire operation will fail with an error (site may exist but Pulumi will report failure). Recommendation: Set to false for initial site creation, then enable after first manual publish.
	Publish *bool `pulumi:"publish"`
	// The slugified version of the site name used in URLs and for file organization. Optional - if not provided, Webflow will automatically generate one from the displayName. Must use only lowercase letters (a-z), numbers (0-9), and hyphens (-). No spaces, underscores, or special characters allowed. Must start and end with a letter or number (no leading/trailing hyphens). Examples: 'my-site', 'company-blog-2024', 'product-landing-page'.
	ShortName *string `pulumi:"shortName"`
	// The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **WARNING: This field is IMMUTABLE.** Once set, it cannot be changed. Changing this value will trigger a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
	TemplateName *string `pulumi:"templateName"`
	// The IANA timezone identifier for the site. Optional - Webflow will use its default timezone if not specified. Use standard IANA timezone identifiers (e.g., 'America/New_York', 'Europe/London', 'Asia/Tokyo', 'UTC'). This timezone is used for scheduling, analytics, and other time-sensitive features.
	TimeZone *string `pulumi:"timeZone"`
	// The Webflow workspace ID where the site will be created. Required for site creation (Enterprise workspace required by Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace.
	WorkspaceId string `pulumi:"workspaceId"`
}

// The set of arguments for constructing a Site resource.
type SiteArgs struct {
	// The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
	DisplayName pulumi.StringInput
	// The folder ID where the site will be organized in the Webflow dashboard. Optional - the site will be placed at the workspace root if not specified. This is useful for organizing multiple sites into logical groups within your workspace.
	ParentFolderId pulumi.StringPtrInput
	// Automatically publish the site after creation or updates. When set to true, the provider will publish the site to production after successfully creating or updating it. Default: false (manual publishing required). Note: Site must have at least one published version before automatic publishing will work. If publishing fails, the entire operation will fail with an error (site may exist but Pulumi will report failure). Recommendation: Set to false for initial site creation, then enable after first manual publish.
	Publish pulumi.BoolPtrInput
	// The slugified version of the site name used in URLs and for file organization. Optional - if not provided, Webflow will automatically generate one from the displayName. Must use only lowercase letters (a-z), numbers (0-9), and hyphens (-). No spaces, underscores, or special characters allowed. Must start and end with a letter or number (no leading/trailing hyphens). Examples: 'my-site', 'company-blog-2024', 'product-landing-page'.
	ShortName pulumi.StringPtrInput
	// The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **WARNING: This field is IMMUTABLE.** Once set, it cannot be changed. Changing this value will trigger a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
	TemplateName pulumi.StringPtrInput
	// The IANA timezone identifier for the site. Optional - Webflow will use its default timezone if not specified. Use standard IANA timezone identifiers (e.g., 'America/New_York', 'Europe/London', 'Asia/Tokyo', 'UTC'). This timezone is used for scheduling, analytics, and other time-sensitive features.
	TimeZone pulumi.StringPtrInput
	// The Webflow workspace ID where the site will be created. Required for site creation (Enterprise workspace required by Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace.
	WorkspaceId pulumi.StringInput
}

func (SiteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*siteArgs)(nil)).Elem()
}

type SiteInput interface {
	pulumi.Input

	ToSiteOutput() SiteOutput
	ToSiteOutputWithContext(ctx context.Context) SiteOutput
}

func (*Site) ElementType() reflect.Type {
	return reflect.TypeOf((**Site)(nil)).Elem()
}

func (i *Site) ToSiteOutput() SiteOutput {
	return i.ToSiteOutputWithContext(context.Background())
}

func (i *Site) ToSiteOutputWithContext(ctx context.Context) SiteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SiteOutput)
}

type SiteOutput struct{ *pulumi.OutputState }

func (SiteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Site)(nil)).Elem()
}

func (o SiteOutput) ToSiteOutput() SiteOutput {
	return o
}

func (o SiteOutput) ToSiteOutputWithContext(ctx context.Context) SiteOutput {
	return o
}

// List of custom domains attached to the site (read-only in this release). Custom domain management will be available in a future release.
func (o SiteOutput) CustomDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Site) pulumi.StringArrayOutput { return v.CustomDomains }).(pulumi.StringArrayOutput)
}

// Indicates whether data collection is enabled for this site (read-only). Controlled by your Webflow workspace settings, not per-site.
func (o SiteOutput) DataCollectionEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.BoolPtrOutput { return v.DataCollectionEnabled }).(pulumi.BoolPtrOutput)
}

// The type of data collection enabled for the site (read-only). Possible values: 'always' (always collect), 'optOut' (collect by default), 'disabled' (no collection). Controlled by your Webflow workspace settings, not per-site.
func (o SiteOutput) DataCollectionType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.DataCollectionType }).(pulumi.StringPtrOutput)
}

// The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
func (o SiteOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *Site) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// The RFC3339 timestamp of the last time the site was published (read-only). Automatically set by Webflow when changes are published to production.
func (o SiteOutput) LastPublished() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.LastPublished }).(pulumi.StringPtrOutput)
}

// The RFC3339 timestamp of the last time the site configuration was updated (read-only). Automatically set by Webflow when any site changes occur.
func (o SiteOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// The folder ID where the site will be organized in the Webflow dashboard. Optional - the site will be placed at the workspace root if not specified. This is useful for organizing multiple sites into logical groups within your workspace.
func (o SiteOutput) ParentFolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.ParentFolderId }).(pulumi.StringPtrOutput)
}

// The URL to a preview image of the site (read-only). Automatically generated by Webflow for site thumbnails in the dashboard.
func (o SiteOutput) PreviewUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.PreviewUrl }).(pulumi.StringPtrOutput)
}

// Automatically publish the site after creation or updates. When set to true, the provider will publish the site to production after successfully creating or updating it. Default: false (manual publishing required). Note: Site must have at least one published version before automatic publishing will work. If publishing fails, the entire operation will fail with an error (site may exist but Pulumi will report failure). Recommendation: Set to false for initial site creation, then enable after first manual publish.
func (o SiteOutput) Publish() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.BoolPtrOutput { return v.Publish }).(pulumi.BoolPtrOutput)
}

// The slugified version of the site name used in URLs and for file organization. Optional - if not provided, Webflow will automatically generate one from the displayName. Must use only lowercase letters (a-z), numbers (0-9), and hyphens (-). No spaces, underscores, or special characters allowed. Must start and end with a letter or number (no leading/trailing hyphens). Examples: 'my-site', 'company-blog-2024', 'product-landing-page'.
func (o SiteOutput) ShortName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.ShortName }).(pulumi.StringPtrOutput)
}

// The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **WARNING: This field is IMMUTABLE.** Once set, it cannot be changed. Changing this value will trigger a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
func (o SiteOutput) TemplateName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.TemplateName }).(pulumi.StringPtrOutput)
}

// The IANA timezone identifier for the site. Optional - Webflow will use its default timezone if not specified. Use standard IANA timezone identifiers (e.g., 'America/New_York', 'Europe/London', 'Asia/Tokyo', 'UTC'). This timezone is used for scheduling, analytics, and other time-sensitive features.
func (o SiteOutput) TimeZone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Site) pulumi.StringPtrOutput { return v.TimeZone }).(pulumi.StringPtrOutput)
}

// The Webflow workspace ID where the site will be created. Required for site creation (Enterprise workspace required by Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace.
func (o SiteOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *Site) pulumi.StringOutput { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SiteInput)(nil)).Elem(), &Site{})
	pulumi.RegisterOutputType(SiteOutput{})
}
