// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages users for a Webflow site. This resource allows you to invite users to your site with specified access groups. Users will receive an invitation email and must accept it to access paid content. Note: The user's email cannot be changed after creation.
type User struct {
	pulumi.CustomResourceState

	// Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type 'admin' (assigned via API or designer). Example: ['premium-members', 'beta-testers']. Access group slugs can be found in the Webflow dashboard under Users > Access Groups.
	AccessGroups pulumi.StringArrayOutput `pulumi:"accessGroups"`
	// The timestamp when the user was created (RFC3339 format). This is automatically set and is read-only.
	CreatedOn pulumi.StringPtrOutput `pulumi:"createdOn"`
	// The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
	Email pulumi.StringOutput `pulumi:"email"`
	// The timestamp when the user was invited (RFC3339 format). This is automatically set and is read-only.
	InvitedOn pulumi.StringPtrOutput `pulumi:"invitedOn"`
	// Indicates whether the user has verified their email address. This is read-only and set by Webflow when the user verifies their email.
	IsEmailVerified pulumi.BoolPtrOutput `pulumi:"isEmailVerified"`
	// The timestamp when the user last logged in (RFC3339 format). This is read-only.
	LastLogin pulumi.StringPtrOutput `pulumi:"lastLogin"`
	// The timestamp when the user was last updated (RFC3339 format). This is read-only.
	LastUpdated pulumi.StringPtrOutput `pulumi:"lastUpdated"`
	// Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId pulumi.StringOutput `pulumi:"siteId"`
	// The status of the user. Possible values: 'invited' (invitation sent but not accepted), 'verified' (email verified), 'unverified' (registered but email not verified). This is read-only.
	Status pulumi.StringPtrOutput `pulumi:"status"`
	// The Webflow-assigned unique identifier for this user. This is automatically assigned when the user is created and is read-only.
	UserId pulumi.StringPtrOutput `pulumi:"userId"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("webflow:index:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("webflow:index:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
}

type UserState struct {
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type 'admin' (assigned via API or designer). Example: ['premium-members', 'beta-testers']. Access group slugs can be found in the Webflow dashboard under Users > Access Groups.
	AccessGroups []string `pulumi:"accessGroups"`
	// The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
	Email string `pulumi:"email"`
	// Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
	Name *string `pulumi:"name"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId string `pulumi:"siteId"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type 'admin' (assigned via API or designer). Example: ['premium-members', 'beta-testers']. Access group slugs can be found in the Webflow dashboard under Users > Access Groups.
	AccessGroups pulumi.StringArrayInput
	// The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
	Email pulumi.StringInput
	// Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
	Name pulumi.StringPtrInput
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId pulumi.StringInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type 'admin' (assigned via API or designer). Example: ['premium-members', 'beta-testers']. Access group slugs can be found in the Webflow dashboard under Users > Access Groups.
func (o UserOutput) AccessGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.AccessGroups }).(pulumi.StringArrayOutput)
}

// The timestamp when the user was created (RFC3339 format). This is automatically set and is read-only.
func (o UserOutput) CreatedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.CreatedOn }).(pulumi.StringPtrOutput)
}

// The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
func (o UserOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// The timestamp when the user was invited (RFC3339 format). This is automatically set and is read-only.
func (o UserOutput) InvitedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.InvitedOn }).(pulumi.StringPtrOutput)
}

// Indicates whether the user has verified their email address. This is read-only and set by Webflow when the user verifies their email.
func (o UserOutput) IsEmailVerified() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.IsEmailVerified }).(pulumi.BoolPtrOutput)
}

// The timestamp when the user last logged in (RFC3339 format). This is read-only.
func (o UserOutput) LastLogin() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.LastLogin }).(pulumi.StringPtrOutput)
}

// The timestamp when the user was last updated (RFC3339 format). This is read-only.
func (o UserOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
func (o UserOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
func (o UserOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

// The status of the user. Possible values: 'invited' (invitation sent but not accepted), 'verified' (email verified), 'unverified' (registered but email not verified). This is read-only.
func (o UserOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Status }).(pulumi.StringPtrOutput)
}

// The Webflow-assigned unique identifier for this user. This is automatically assigned when the user is created and is read-only.
func (o UserOutput) UserId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.UserId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterOutputType(UserOutput{})
}
