// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// DEPRECATED: The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run "pulumi state delete <URN>" to clean up existing state.
//
// Deprecated: The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run "pulumi state delete <URN>" to clean up existing state.
type User struct {
	pulumi.CustomResourceState

	// Access group slugs assigned to the user.
	AccessGroups pulumi.StringArrayOutput `pulumi:"accessGroups"`
	// Timestamp when the user was created.
	CreatedOn pulumi.StringPtrOutput `pulumi:"createdOn"`
	// The email address of the user.
	Email pulumi.StringOutput `pulumi:"email"`
	// Timestamp when the user was invited.
	InvitedOn pulumi.StringPtrOutput `pulumi:"invitedOn"`
	// Whether the user has verified their email.
	IsEmailVerified pulumi.BoolPtrOutput `pulumi:"isEmailVerified"`
	// Timestamp when the user last logged in.
	LastLogin pulumi.StringPtrOutput `pulumi:"lastLogin"`
	// Timestamp when the user was last updated.
	LastUpdated pulumi.StringPtrOutput `pulumi:"lastUpdated"`
	// Display name for the user.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// The Webflow site ID.
	SiteId pulumi.StringOutput `pulumi:"siteId"`
	// The user's status.
	Status pulumi.StringPtrOutput `pulumi:"status"`
	// The Webflow-assigned user ID.
	UserId pulumi.StringPtrOutput `pulumi:"userId"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("webflow:index:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("webflow:index:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
}

type UserState struct {
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// Access group slugs assigned to the user.
	AccessGroups []string `pulumi:"accessGroups"`
	// The email address of the user.
	Email string `pulumi:"email"`
	// Display name for the user.
	Name *string `pulumi:"name"`
	// The Webflow site ID.
	SiteId string `pulumi:"siteId"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// Access group slugs assigned to the user.
	AccessGroups pulumi.StringArrayInput
	// The email address of the user.
	Email pulumi.StringInput
	// Display name for the user.
	Name pulumi.StringPtrInput
	// The Webflow site ID.
	SiteId pulumi.StringInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// Access group slugs assigned to the user.
func (o UserOutput) AccessGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.AccessGroups }).(pulumi.StringArrayOutput)
}

// Timestamp when the user was created.
func (o UserOutput) CreatedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.CreatedOn }).(pulumi.StringPtrOutput)
}

// The email address of the user.
func (o UserOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// Timestamp when the user was invited.
func (o UserOutput) InvitedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.InvitedOn }).(pulumi.StringPtrOutput)
}

// Whether the user has verified their email.
func (o UserOutput) IsEmailVerified() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.IsEmailVerified }).(pulumi.BoolPtrOutput)
}

// Timestamp when the user last logged in.
func (o UserOutput) LastLogin() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.LastLogin }).(pulumi.StringPtrOutput)
}

// Timestamp when the user was last updated.
func (o UserOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// Display name for the user.
func (o UserOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// The Webflow site ID.
func (o UserOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

// The user's status.
func (o UserOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Status }).(pulumi.StringPtrOutput)
}

// The Webflow-assigned user ID.
func (o UserOutput) UserId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.UserId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterOutputType(UserOutput{})
}
