// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.webflow.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.webflow.webflow.CollectionItemArgs;
import com.webflow.webflow.Utilities;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages CMS collection items for a Webflow collection. Collection items represent individual content entries (blog posts, products, etc.) within a CMS collection. Each item has dynamic field data based on the collection schema.
 * 
 */
@ResourceType(type="webflow:index:CollectionItem")
public class CollectionItem extends com.pulumi.resources.CustomResource {
    /**
     * The locale ID for localized sites (optional, e.g., &#39;en-US&#39;). Only required if your site uses Webflow&#39;s localization features. Leave empty for non-localized sites.
     * 
     */
    @Export(name="cmsLocaleId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cmsLocaleId;

    /**
     * @return The locale ID for localized sites (optional, e.g., &#39;en-US&#39;). Only required if your site uses Webflow&#39;s localization features. Leave empty for non-localized sites.
     * 
     */
    public Output<Optional<String>> cmsLocaleId() {
        return Codegen.optional(this.cmsLocaleId);
    }
    /**
     * The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
     * 
     */
    @Export(name="collectionId", refs={String.class}, tree="[0]")
    private Output<String> collectionId;

    /**
     * @return The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
     * 
     */
    public Output<String> collectionId() {
        return this.collectionId;
    }
    /**
     * The timestamp when the item was created (RFC3339 format, read-only). This is automatically set by Webflow and is immutable.
     * 
     */
    @Export(name="createdOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdOn;

    /**
     * @return The timestamp when the item was created (RFC3339 format, read-only). This is automatically set by Webflow and is immutable.
     * 
     */
    public Output<Optional<String>> createdOn() {
        return Codegen.optional(this.createdOn);
    }
    /**
     * A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include &#39;name&#39; (required), &#39;slug&#39; (required, URL-friendly), and any custom fields you&#39;ve added to the collection. Example: {&#34;name&#34;: &#34;My Blog Post&#34;, &#34;slug&#34;: &#34;my-blog-post&#34;, &#34;content&#34;: &#34;Post content...&#34;}
     * 
     */
    @Export(name="fieldData", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> fieldData;

    /**
     * @return A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include &#39;name&#39; (required), &#39;slug&#39; (required, URL-friendly), and any custom fields you&#39;ve added to the collection. Example: {&#34;name&#34;: &#34;My Blog Post&#34;, &#34;slug&#34;: &#34;my-blog-post&#34;, &#34;content&#34;: &#34;Post content...&#34;}
     * 
     */
    public Output<Map<String,Object>> fieldData() {
        return this.fieldData;
    }
    /**
     * Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
     * 
     */
    @Export(name="isArchived", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isArchived;

    /**
     * @return Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
     * 
     */
    public Output<Optional<Boolean>> isArchived() {
        return Codegen.optional(this.isArchived);
    }
    /**
     * Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
     * 
     */
    @Export(name="isDraft", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isDraft;

    /**
     * @return Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
     * 
     */
    public Output<Optional<Boolean>> isDraft() {
        return Codegen.optional(this.isDraft);
    }
    /**
     * The Webflow-assigned item ID (read-only). This is automatically set by Webflow when the item is created.
     * 
     */
    @Export(name="itemId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> itemId;

    /**
     * @return The Webflow-assigned item ID (read-only). This is automatically set by Webflow when the item is created.
     * 
     */
    public Output<Optional<String>> itemId() {
        return Codegen.optional(this.itemId);
    }
    /**
     * The timestamp when the item was last published (RFC3339 format, read-only). This is automatically updated by Webflow when the item is published.
     * 
     */
    @Export(name="lastPublished", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastPublished;

    /**
     * @return The timestamp when the item was last published (RFC3339 format, read-only). This is automatically updated by Webflow when the item is published.
     * 
     */
    public Output<Optional<String>> lastPublished() {
        return Codegen.optional(this.lastPublished);
    }
    /**
     * The timestamp when the item was last updated (RFC3339 format, read-only). This is automatically updated by Webflow whenever the item is modified.
     * 
     */
    @Export(name="lastUpdated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastUpdated;

    /**
     * @return The timestamp when the item was last updated (RFC3339 format, read-only). This is automatically updated by Webflow whenever the item is modified.
     * 
     */
    public Output<Optional<String>> lastUpdated() {
        return Codegen.optional(this.lastUpdated);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CollectionItem(java.lang.String name) {
        this(name, CollectionItemArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CollectionItem(java.lang.String name, CollectionItemArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CollectionItem(java.lang.String name, CollectionItemArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:CollectionItem", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private CollectionItem(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:CollectionItem", name, null, makeResourceOptions(options, id), false);
    }

    private static CollectionItemArgs makeArgs(CollectionItemArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? CollectionItemArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CollectionItem get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CollectionItem(name, id, options);
    }
}
