// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.webflow.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.webflow.webflow.inputs.CustomScriptArgsArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class SiteCustomCodeArgs extends com.pulumi.resources.ResourceArgs {

    public static final SiteCustomCodeArgs Empty = new SiteCustomCodeArgs();

    /**
     * A list of custom scripts to apply to the site. Each script must be registered to the site first. To remove individual scripts, simply exclude them from this list on the next update. If you have multiple scripts your app manages, ensure they are always included in this list.
     * 
     */
    @Import(name="scripts", required=true)
    private Output<List<CustomScriptArgsArgs>> scripts;

    /**
     * @return A list of custom scripts to apply to the site. Each script must be registered to the site first. To remove individual scripts, simply exclude them from this list on the next update. If you have multiple scripts your app manages, ensure they are always included in this list.
     * 
     */
    public Output<List<CustomScriptArgsArgs>> scripts() {
        return this.scripts;
    }

    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Import(name="siteId", required=true)
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }

    private SiteCustomCodeArgs() {}

    private SiteCustomCodeArgs(SiteCustomCodeArgs $) {
        this.scripts = $.scripts;
        this.siteId = $.siteId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SiteCustomCodeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SiteCustomCodeArgs $;

        public Builder() {
            $ = new SiteCustomCodeArgs();
        }

        public Builder(SiteCustomCodeArgs defaults) {
            $ = new SiteCustomCodeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param scripts A list of custom scripts to apply to the site. Each script must be registered to the site first. To remove individual scripts, simply exclude them from this list on the next update. If you have multiple scripts your app manages, ensure they are always included in this list.
         * 
         * @return builder
         * 
         */
        public Builder scripts(Output<List<CustomScriptArgsArgs>> scripts) {
            $.scripts = scripts;
            return this;
        }

        /**
         * @param scripts A list of custom scripts to apply to the site. Each script must be registered to the site first. To remove individual scripts, simply exclude them from this list on the next update. If you have multiple scripts your app manages, ensure they are always included in this list.
         * 
         * @return builder
         * 
         */
        public Builder scripts(List<CustomScriptArgsArgs> scripts) {
            return scripts(Output.of(scripts));
        }

        /**
         * @param scripts A list of custom scripts to apply to the site. Each script must be registered to the site first. To remove individual scripts, simply exclude them from this list on the next update. If you have multiple scripts your app manages, ensure they are always included in this list.
         * 
         * @return builder
         * 
         */
        public Builder scripts(CustomScriptArgsArgs... scripts) {
            return scripts(List.of(scripts));
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(Output<String> siteId) {
            $.siteId = siteId;
            return this;
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(String siteId) {
            return siteId(Output.of(siteId));
        }

        public SiteCustomCodeArgs build() {
            if ($.scripts == null) {
                throw new MissingRequiredPropertyException("SiteCustomCodeArgs", "scripts");
            }
            if ($.siteId == null) {
                throw new MissingRequiredPropertyException("SiteCustomCodeArgs", "siteId");
            }
            return $;
        }
    }

}
