// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.webflow.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class WebhookArgs extends com.pulumi.resources.ResourceArgs {

    public static final WebhookArgs Empty = new WebhookArgs();

    /**
     * Optional filter for webhook events. The structure depends on the triggerType and allows you to receive only specific events. For example, for collection_item_created, you can filter by collection ID. Refer to Webflow API documentation for filter options for each trigger type.
     * 
     */
    @Import(name="filter")
    private @Nullable Output<Map<String,Object>> filter;

    /**
     * @return Optional filter for webhook events. The structure depends on the triggerType and allows you to receive only specific events. For example, for collection_item_created, you can filter by collection ID. Refer to Webflow API documentation for filter options for each trigger type.
     * 
     */
    public Optional<Output<Map<String,Object>>> filter() {
        return Optional.ofNullable(this.filter);
    }

    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Import(name="siteId", required=true)
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }

    /**
     * The Webflow event that triggers this webhook. Valid values: form_submission, site_publish, page_created, page_metadata_updated, page_deleted, ecomm_new_order, ecomm_order_changed, ecomm_inventory_changed, memberships_user_account_added, memberships_user_account_updated, memberships_user_account_deleted, collection_item_created, collection_item_changed, collection_item_deleted, collection_item_unpublished. Example: &#39;form_submission&#39; to receive notifications when forms are submitted.
     * 
     */
    @Import(name="triggerType", required=true)
    private Output<String> triggerType;

    /**
     * @return The Webflow event that triggers this webhook. Valid values: form_submission, site_publish, page_created, page_metadata_updated, page_deleted, ecomm_new_order, ecomm_order_changed, ecomm_inventory_changed, memberships_user_account_added, memberships_user_account_updated, memberships_user_account_deleted, collection_item_created, collection_item_changed, collection_item_deleted, collection_item_unpublished. Example: &#39;form_submission&#39; to receive notifications when forms are submitted.
     * 
     */
    public Output<String> triggerType() {
        return this.triggerType;
    }

    /**
     * The HTTPS endpoint where Webflow will send webhook events (e.g., &#39;https://example.com/webhooks/webflow&#39;, &#39;https://api.example.com/events&#39;). Must be a valid HTTPS URL. Webflow requires HTTPS for security. Your endpoint should accept POST requests with JSON payloads containing event data.
     * 
     */
    @Import(name="url", required=true)
    private Output<String> url;

    /**
     * @return The HTTPS endpoint where Webflow will send webhook events (e.g., &#39;https://example.com/webhooks/webflow&#39;, &#39;https://api.example.com/events&#39;). Must be a valid HTTPS URL. Webflow requires HTTPS for security. Your endpoint should accept POST requests with JSON payloads containing event data.
     * 
     */
    public Output<String> url() {
        return this.url;
    }

    private WebhookArgs() {}

    private WebhookArgs(WebhookArgs $) {
        this.filter = $.filter;
        this.siteId = $.siteId;
        this.triggerType = $.triggerType;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(WebhookArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private WebhookArgs $;

        public Builder() {
            $ = new WebhookArgs();
        }

        public Builder(WebhookArgs defaults) {
            $ = new WebhookArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filter Optional filter for webhook events. The structure depends on the triggerType and allows you to receive only specific events. For example, for collection_item_created, you can filter by collection ID. Refer to Webflow API documentation for filter options for each trigger type.
         * 
         * @return builder
         * 
         */
        public Builder filter(@Nullable Output<Map<String,Object>> filter) {
            $.filter = filter;
            return this;
        }

        /**
         * @param filter Optional filter for webhook events. The structure depends on the triggerType and allows you to receive only specific events. For example, for collection_item_created, you can filter by collection ID. Refer to Webflow API documentation for filter options for each trigger type.
         * 
         * @return builder
         * 
         */
        public Builder filter(Map<String,Object> filter) {
            return filter(Output.of(filter));
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(Output<String> siteId) {
            $.siteId = siteId;
            return this;
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(String siteId) {
            return siteId(Output.of(siteId));
        }

        /**
         * @param triggerType The Webflow event that triggers this webhook. Valid values: form_submission, site_publish, page_created, page_metadata_updated, page_deleted, ecomm_new_order, ecomm_order_changed, ecomm_inventory_changed, memberships_user_account_added, memberships_user_account_updated, memberships_user_account_deleted, collection_item_created, collection_item_changed, collection_item_deleted, collection_item_unpublished. Example: &#39;form_submission&#39; to receive notifications when forms are submitted.
         * 
         * @return builder
         * 
         */
        public Builder triggerType(Output<String> triggerType) {
            $.triggerType = triggerType;
            return this;
        }

        /**
         * @param triggerType The Webflow event that triggers this webhook. Valid values: form_submission, site_publish, page_created, page_metadata_updated, page_deleted, ecomm_new_order, ecomm_order_changed, ecomm_inventory_changed, memberships_user_account_added, memberships_user_account_updated, memberships_user_account_deleted, collection_item_created, collection_item_changed, collection_item_deleted, collection_item_unpublished. Example: &#39;form_submission&#39; to receive notifications when forms are submitted.
         * 
         * @return builder
         * 
         */
        public Builder triggerType(String triggerType) {
            return triggerType(Output.of(triggerType));
        }

        /**
         * @param url The HTTPS endpoint where Webflow will send webhook events (e.g., &#39;https://example.com/webhooks/webflow&#39;, &#39;https://api.example.com/events&#39;). Must be a valid HTTPS URL. Webflow requires HTTPS for security. Your endpoint should accept POST requests with JSON payloads containing event data.
         * 
         * @return builder
         * 
         */
        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url The HTTPS endpoint where Webflow will send webhook events (e.g., &#39;https://example.com/webhooks/webflow&#39;, &#39;https://api.example.com/events&#39;). Must be a valid HTTPS URL. Webflow requires HTTPS for security. Your endpoint should accept POST requests with JSON payloads containing event data.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        public WebhookArgs build() {
            if ($.siteId == null) {
                throw new MissingRequiredPropertyException("WebhookArgs", "siteId");
            }
            if ($.triggerType == null) {
                throw new MissingRequiredPropertyException("WebhookArgs", "triggerType");
            }
            if ($.url == null) {
                throw new MissingRequiredPropertyException("WebhookArgs", "url");
            }
            return $;
        }
    }

}
