// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;




public final class GetTokenInfoPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetTokenInfoPlainArgs Empty = new GetTokenInfoPlainArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetTokenInfoPlainArgs $;

        public Builder() {
            $ = new GetTokenInfoPlainArgs();
        }
        public GetTokenInfoPlainArgs build() {
            return $;
        }
    }

}
