// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;


public final class PageCustomCodeScriptArgs extends com.pulumi.resources.ResourceArgs {

    public static final PageCustomCodeScriptArgs Empty = new PageCustomCodeScriptArgs();

    /**
     * Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
     * 
     */
    @Import(name="attributes", required=true)
    private Output<Map<String,Object>> attributes;

    /**
     * @return Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
     * 
     */
    public Output<Map<String,Object>> attributes() {
        return this.attributes;
    }

    /**
     * The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * Where the script should be applied on the page. Must be either &#39;header&#39; (loaded in page header) or &#39;footer&#39; (loaded at end of page). Use &#39;header&#39; for scripts that don&#39;t depend on DOM elements. Use &#39;footer&#39; for scripts that need to run after DOM is fully loaded.
     * 
     */
    @Import(name="location", required=true)
    private Output<String> location;

    /**
     * @return Where the script should be applied on the page. Must be either &#39;header&#39; (loaded in page header) or &#39;footer&#39; (loaded at end of page). Use &#39;header&#39; for scripts that don&#39;t depend on DOM elements. Use &#39;footer&#39; for scripts that need to run after DOM is fully loaded.
     * 
     */
    public Output<String> location() {
        return this.location;
    }

    /**
     * The semantic version string for the registered script (e.g., &#39;1.0.0&#39;). This version must match a registered version of the script. You can have multiple versions of the same script registered.
     * 
     */
    @Import(name="scriptVersion", required=true)
    private Output<String> scriptVersion;

    /**
     * @return The semantic version string for the registered script (e.g., &#39;1.0.0&#39;). This version must match a registered version of the script. You can have multiple versions of the same script registered.
     * 
     */
    public Output<String> scriptVersion() {
        return this.scriptVersion;
    }

    private PageCustomCodeScriptArgs() {}

    private PageCustomCodeScriptArgs(PageCustomCodeScriptArgs $) {
        this.attributes = $.attributes;
        this.id = $.id;
        this.location = $.location;
        this.scriptVersion = $.scriptVersion;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PageCustomCodeScriptArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PageCustomCodeScriptArgs $;

        public Builder() {
            $ = new PageCustomCodeScriptArgs();
        }

        public Builder(PageCustomCodeScriptArgs defaults) {
            $ = new PageCustomCodeScriptArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param attributes Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
         * 
         * @return builder
         * 
         */
        public Builder attributes(Output<Map<String,Object>> attributes) {
            $.attributes = attributes;
            return this;
        }

        /**
         * @param attributes Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
         * 
         * @return builder
         * 
         */
        public Builder attributes(Map<String,Object> attributes) {
            return attributes(Output.of(attributes));
        }

        /**
         * @param id The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param location Where the script should be applied on the page. Must be either &#39;header&#39; (loaded in page header) or &#39;footer&#39; (loaded at end of page). Use &#39;header&#39; for scripts that don&#39;t depend on DOM elements. Use &#39;footer&#39; for scripts that need to run after DOM is fully loaded.
         * 
         * @return builder
         * 
         */
        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location Where the script should be applied on the page. Must be either &#39;header&#39; (loaded in page header) or &#39;footer&#39; (loaded at end of page). Use &#39;header&#39; for scripts that don&#39;t depend on DOM elements. Use &#39;footer&#39; for scripts that need to run after DOM is fully loaded.
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param scriptVersion The semantic version string for the registered script (e.g., &#39;1.0.0&#39;). This version must match a registered version of the script. You can have multiple versions of the same script registered.
         * 
         * @return builder
         * 
         */
        public Builder scriptVersion(Output<String> scriptVersion) {
            $.scriptVersion = scriptVersion;
            return this;
        }

        /**
         * @param scriptVersion The semantic version string for the registered script (e.g., &#39;1.0.0&#39;). This version must match a registered version of the script. You can have multiple versions of the same script registered.
         * 
         * @return builder
         * 
         */
        public Builder scriptVersion(String scriptVersion) {
            return scriptVersion(Output.of(scriptVersion));
        }

        public PageCustomCodeScriptArgs build() {
            if ($.attributes == null) {
                throw new MissingRequiredPropertyException("PageCustomCodeScriptArgs", "attributes");
            }
            if ($.id == null) {
                throw new MissingRequiredPropertyException("PageCustomCodeScriptArgs", "id");
            }
            if ($.location == null) {
                throw new MissingRequiredPropertyException("PageCustomCodeScriptArgs", "location");
            }
            if ($.scriptVersion == null) {
                throw new MissingRequiredPropertyException("PageCustomCodeScriptArgs", "scriptVersion");
            }
            return $;
        }
    }

}
