template: native
provider: webflow
major-version: 0
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/jdetmar/pulumi-webflow/provider.Version
parallel: 3
sdkModuleDir: sdk/go/webflow
esc:
    enabled: true
    environment: imports/github-secrets
envOverride:
    FOO: BAR
