# Webflow Pulumi Provider - GoReleaser Configuration
project_name: pulumi-webflow
builds:
- id: build-provider
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  ignore: &a1 []
  main: ./cmd/pulumi-resource-webflow/
  ldflags: &a2
    - -s
    - -w
    - -X
      github.com/jdetmar/pulumi-webflow/provider.Version={{.Tag}}
  binary: pulumi-resource-webflow
- id: build-provider-sign-windows
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - windows
  goarch:
  - amd64
  - arm64
  ignore: *a1
  main: ./cmd/pulumi-resource-webflow/
  ldflags: *a2
  binary: pulumi-resource-webflow
  hooks:
    post:
    - make sign-goreleaser-exe-{{ .Arch }}
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  id: archive
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  disable: false
blobs:
- provider: s3
  region: us-west-2
  bucket: get.pulumi.com
  folder: releases/plugins/
  ids:
  - archive
