project_name: pulumi-webflow

builds:
  - id: build-provider
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore: []
    main: ./cmd/pulumi-resource-pulumi-webflow/
    ldflags:
      - -s
      - -w
      - -X github.com/jdetmar/pulumi-webflow/provider/pkg/version.Version={{.Tag}}
    binary: pulumi-resource-pulumi-webflow

archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    id: archive

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

changelog:
  disable: true

release:
  disable: false
  prerelease: auto
