// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow.Inputs
{

    public sealed class NodeContentUpdateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
        /// </summary>
        [Input("nodeId", required: true)]
        public Input<string> NodeId { get; set; } = null!;

        /// <summary>
        /// The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
        /// </summary>
        [Input("text", required: true)]
        public Input<string> Text { get; set; } = null!;

        public NodeContentUpdateArgs()
        {
        }
        public static new NodeContentUpdateArgs Empty => new NodeContentUpdateArgs();
    }
}
