// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow.Inputs
{

    public sealed class PageCustomCodeScriptArgs : global::Pulumi.ResourceArgs
    {
        [Input("attributes", required: true)]
        private InputMap<object>? _attributes;

        /// <summary>
        /// Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
        /// </summary>
        public InputMap<object> Attributes
        {
            get => _attributes ?? (_attributes = new InputMap<object>());
            set => _attributes = value;
        }

        /// <summary>
        /// The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Where the script should be applied on the page. Must be either 'header' (loaded in page header) or 'footer' (loaded at end of page). Use 'header' for scripts that don't depend on DOM elements. Use 'footer' for scripts that need to run after DOM is fully loaded.
        /// </summary>
        [Input("location", required: true)]
        public Input<string> Location { get; set; } = null!;

        /// <summary>
        /// The semantic version string for the registered script (e.g., '1.0.0'). This version must match a registered version of the script. You can have multiple versions of the same script registered.
        /// </summary>
        [Input("scriptVersion", required: true)]
        public Input<string> ScriptVersion { get; set; } = null!;

        public PageCustomCodeScriptArgs()
        {
        }
        public static new PageCustomCodeScriptArgs Empty => new PageCustomCodeScriptArgs();
    }
}
