// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Webflow
{
    /// <summary>
    /// Manages custom code (JavaScript) scripts applied to a Webflow page. This resource allows you to apply registered custom code scripts to specific pages. Scripts must first be registered using the RegisteredScript resource before they can be applied. All scripts in the configuration will be applied to the page; scripts not listed will be removed.
    /// </summary>
    [WebflowResourceType("webflow:index:PageCustomCode")]
    public partial class PageCustomCode : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when the page custom code was first created (RFC3339 format). This is automatically set when the configuration is first created and is read-only.
        /// </summary>
        [Output("createdOn")]
        public Output<string?> CreatedOn { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the page custom code was last updated (RFC3339 format). This is automatically set when the configuration is updated and is read-only.
        /// </summary>
        [Output("lastUpdated")]
        public Output<string?> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// The Webflow page ID (24-character hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
        /// </summary>
        [Output("pageId")]
        public Output<string> PageId { get; private set; } = null!;

        /// <summary>
        /// List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
        /// </summary>
        [Output("scripts")]
        public Output<ImmutableArray<Outputs.PageCustomCodeScript>> Scripts { get; private set; } = null!;


        /// <summary>
        /// Create a PageCustomCode resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PageCustomCode(string name, PageCustomCodeArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:PageCustomCode", name, args ?? new PageCustomCodeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PageCustomCode(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:PageCustomCode", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PageCustomCode resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PageCustomCode Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PageCustomCode(name, id, options);
        }
    }

    public sealed class PageCustomCodeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Webflow page ID (24-character hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
        /// </summary>
        [Input("pageId", required: true)]
        public Input<string> PageId { get; set; } = null!;

        [Input("scripts", required: true)]
        private InputList<Inputs.PageCustomCodeScriptArgs>? _scripts;

        /// <summary>
        /// List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
        /// </summary>
        public InputList<Inputs.PageCustomCodeScriptArgs> Scripts
        {
            get => _scripts ?? (_scripts = new InputList<Inputs.PageCustomCodeScriptArgs>());
            set => _scripts = value;
        }

        public PageCustomCodeArgs()
        {
        }
        public static new PageCustomCodeArgs Empty => new PageCustomCodeArgs();
    }
}
