// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.webflow.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CustomScriptArgsArgs extends com.pulumi.resources.ResourceArgs {

    public static final CustomScriptArgsArgs Empty = new CustomScriptArgsArgs();

    /**
     * Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {&#39;data-config&#39;: &#39;my-value&#39;}. These attributes are passed directly to the script tag.
     * 
     */
    @Import(name="attributes")
    private @Nullable Output<Map<String,Object>> attributes;

    /**
     * @return Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {&#39;data-config&#39;: &#39;my-value&#39;}. These attributes are passed directly to the script tag.
     * 
     */
    public Optional<Output<Map<String,Object>>> attributes() {
        return Optional.ofNullable(this.attributes);
    }

    /**
     * The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: &#39;cms_slider&#39;, &#39;analytics&#39;, &#39;custom_widget&#39;
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: &#39;cms_slider&#39;, &#39;analytics&#39;, &#39;custom_widget&#39;
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * The location where the script is placed on the page. Valid values: &#39;header&#39; (placed in the &lt;head&gt; section), &#39;footer&#39; (placed before &lt;/body&gt;). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
     * 
     */
    @Import(name="location", required=true)
    private Output<String> location;

    /**
     * @return The location where the script is placed on the page. Valid values: &#39;header&#39; (placed in the &lt;head&gt; section), &#39;footer&#39; (placed before &lt;/body&gt;). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
     * 
     */
    public Output<String> location() {
        return this.location;
    }

    /**
     * The semantic version string for the registered script (e.g., &#39;1.0.0&#39;, &#39;0.1.2&#39;). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
     * 
     */
    @Import(name="version", required=true)
    private Output<String> version;

    /**
     * @return The semantic version string for the registered script (e.g., &#39;1.0.0&#39;, &#39;0.1.2&#39;). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
     * 
     */
    public Output<String> version() {
        return this.version;
    }

    private CustomScriptArgsArgs() {}

    private CustomScriptArgsArgs(CustomScriptArgsArgs $) {
        this.attributes = $.attributes;
        this.id = $.id;
        this.location = $.location;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CustomScriptArgsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CustomScriptArgsArgs $;

        public Builder() {
            $ = new CustomScriptArgsArgs();
        }

        public Builder(CustomScriptArgsArgs defaults) {
            $ = new CustomScriptArgsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param attributes Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {&#39;data-config&#39;: &#39;my-value&#39;}. These attributes are passed directly to the script tag.
         * 
         * @return builder
         * 
         */
        public Builder attributes(@Nullable Output<Map<String,Object>> attributes) {
            $.attributes = attributes;
            return this;
        }

        /**
         * @param attributes Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {&#39;data-config&#39;: &#39;my-value&#39;}. These attributes are passed directly to the script tag.
         * 
         * @return builder
         * 
         */
        public Builder attributes(Map<String,Object> attributes) {
            return attributes(Output.of(attributes));
        }

        /**
         * @param id The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: &#39;cms_slider&#39;, &#39;analytics&#39;, &#39;custom_widget&#39;
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: &#39;cms_slider&#39;, &#39;analytics&#39;, &#39;custom_widget&#39;
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param location The location where the script is placed on the page. Valid values: &#39;header&#39; (placed in the &lt;head&gt; section), &#39;footer&#39; (placed before &lt;/body&gt;). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
         * 
         * @return builder
         * 
         */
        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location The location where the script is placed on the page. Valid values: &#39;header&#39; (placed in the &lt;head&gt; section), &#39;footer&#39; (placed before &lt;/body&gt;). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param version The semantic version string for the registered script (e.g., &#39;1.0.0&#39;, &#39;0.1.2&#39;). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
         * 
         * @return builder
         * 
         */
        public Builder version(Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version The semantic version string for the registered script (e.g., &#39;1.0.0&#39;, &#39;0.1.2&#39;). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        public CustomScriptArgsArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("CustomScriptArgsArgs", "id");
            }
            if ($.location == null) {
                throw new MissingRequiredPropertyException("CustomScriptArgsArgs", "location");
            }
            if ($.version == null) {
                throw new MissingRequiredPropertyException("CustomScriptArgsArgs", "version");
            }
            return $;
        }
    }

}
