// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.webflow.webflow.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class NodeContentUpdateArgs extends com.pulumi.resources.ResourceArgs {

    public static final NodeContentUpdateArgs Empty = new NodeContentUpdateArgs();

    /**
     * The unique identifier for the DOM node to update. This ID comes from the page&#39;s DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
     * 
     */
    @Import(name="nodeId", required=true)
    private Output<String> nodeId;

    /**
     * @return The unique identifier for the DOM node to update. This ID comes from the page&#39;s DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
     * 
     */
    public Output<String> nodeId() {
        return this.nodeId;
    }

    /**
     * The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
     * 
     */
    @Import(name="text", required=true)
    private Output<String> text;

    /**
     * @return The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
     * 
     */
    public Output<String> text() {
        return this.text;
    }

    private NodeContentUpdateArgs() {}

    private NodeContentUpdateArgs(NodeContentUpdateArgs $) {
        this.nodeId = $.nodeId;
        this.text = $.text;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NodeContentUpdateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NodeContentUpdateArgs $;

        public Builder() {
            $ = new NodeContentUpdateArgs();
        }

        public Builder(NodeContentUpdateArgs defaults) {
            $ = new NodeContentUpdateArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param nodeId The unique identifier for the DOM node to update. This ID comes from the page&#39;s DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
         * 
         * @return builder
         * 
         */
        public Builder nodeId(Output<String> nodeId) {
            $.nodeId = nodeId;
            return this;
        }

        /**
         * @param nodeId The unique identifier for the DOM node to update. This ID comes from the page&#39;s DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
         * 
         * @return builder
         * 
         */
        public Builder nodeId(String nodeId) {
            return nodeId(Output.of(nodeId));
        }

        /**
         * @param text The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
         * 
         * @return builder
         * 
         */
        public Builder text(Output<String> text) {
            $.text = text;
            return this;
        }

        /**
         * @param text The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
         * 
         * @return builder
         * 
         */
        public Builder text(String text) {
            return text(Output.of(text));
        }

        public NodeContentUpdateArgs build() {
            if ($.nodeId == null) {
                throw new MissingRequiredPropertyException("NodeContentUpdateArgs", "nodeId");
            }
            if ($.text == null) {
                throw new MissingRequiredPropertyException("NodeContentUpdateArgs", "text");
            }
            return $;
        }
    }

}
