// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class NodeContentUpdate {
    /**
     * @return The unique identifier for the DOM node to update. This ID comes from the page&#39;s DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
     * 
     */
    private String nodeId;
    /**
     * @return The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
     * 
     */
    private String text;

    private NodeContentUpdate() {}
    /**
     * @return The unique identifier for the DOM node to update. This ID comes from the page&#39;s DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
     * 
     */
    public String nodeId() {
        return this.nodeId;
    }
    /**
     * @return The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
     * 
     */
    public String text() {
        return this.text;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NodeContentUpdate defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String nodeId;
        private String text;
        public Builder() {}
        public Builder(NodeContentUpdate defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.nodeId = defaults.nodeId;
    	      this.text = defaults.text;
        }

        @CustomType.Setter
        public Builder nodeId(String nodeId) {
            if (nodeId == null) {
              throw new MissingRequiredPropertyException("NodeContentUpdate", "nodeId");
            }
            this.nodeId = nodeId;
            return this;
        }
        @CustomType.Setter
        public Builder text(String text) {
            if (text == null) {
              throw new MissingRequiredPropertyException("NodeContentUpdate", "text");
            }
            this.text = text;
            return this;
        }
        public NodeContentUpdate build() {
            final var _resultValue = new NodeContentUpdate();
            _resultValue.nodeId = nodeId;
            _resultValue.text = text;
            return _resultValue;
        }
    }
}
