// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PageInfo {
    private Boolean archived;
    private @Nullable String collectionId;
    private String createdOn;
    private Boolean draft;
    private String lastUpdated;
    private String pageId;
    private @Nullable String parentId;
    private String siteId;
    private String slug;
    private String title;

    private PageInfo() {}
    public Boolean archived() {
        return this.archived;
    }
    public Optional<String> collectionId() {
        return Optional.ofNullable(this.collectionId);
    }
    public String createdOn() {
        return this.createdOn;
    }
    public Boolean draft() {
        return this.draft;
    }
    public String lastUpdated() {
        return this.lastUpdated;
    }
    public String pageId() {
        return this.pageId;
    }
    public Optional<String> parentId() {
        return Optional.ofNullable(this.parentId);
    }
    public String siteId() {
        return this.siteId;
    }
    public String slug() {
        return this.slug;
    }
    public String title() {
        return this.title;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PageInfo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean archived;
        private @Nullable String collectionId;
        private String createdOn;
        private Boolean draft;
        private String lastUpdated;
        private String pageId;
        private @Nullable String parentId;
        private String siteId;
        private String slug;
        private String title;
        public Builder() {}
        public Builder(PageInfo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.archived = defaults.archived;
    	      this.collectionId = defaults.collectionId;
    	      this.createdOn = defaults.createdOn;
    	      this.draft = defaults.draft;
    	      this.lastUpdated = defaults.lastUpdated;
    	      this.pageId = defaults.pageId;
    	      this.parentId = defaults.parentId;
    	      this.siteId = defaults.siteId;
    	      this.slug = defaults.slug;
    	      this.title = defaults.title;
        }

        @CustomType.Setter
        public Builder archived(Boolean archived) {
            if (archived == null) {
              throw new MissingRequiredPropertyException("PageInfo", "archived");
            }
            this.archived = archived;
            return this;
        }
        @CustomType.Setter
        public Builder collectionId(@Nullable String collectionId) {

            this.collectionId = collectionId;
            return this;
        }
        @CustomType.Setter
        public Builder createdOn(String createdOn) {
            if (createdOn == null) {
              throw new MissingRequiredPropertyException("PageInfo", "createdOn");
            }
            this.createdOn = createdOn;
            return this;
        }
        @CustomType.Setter
        public Builder draft(Boolean draft) {
            if (draft == null) {
              throw new MissingRequiredPropertyException("PageInfo", "draft");
            }
            this.draft = draft;
            return this;
        }
        @CustomType.Setter
        public Builder lastUpdated(String lastUpdated) {
            if (lastUpdated == null) {
              throw new MissingRequiredPropertyException("PageInfo", "lastUpdated");
            }
            this.lastUpdated = lastUpdated;
            return this;
        }
        @CustomType.Setter
        public Builder pageId(String pageId) {
            if (pageId == null) {
              throw new MissingRequiredPropertyException("PageInfo", "pageId");
            }
            this.pageId = pageId;
            return this;
        }
        @CustomType.Setter
        public Builder parentId(@Nullable String parentId) {

            this.parentId = parentId;
            return this;
        }
        @CustomType.Setter
        public Builder siteId(String siteId) {
            if (siteId == null) {
              throw new MissingRequiredPropertyException("PageInfo", "siteId");
            }
            this.siteId = siteId;
            return this;
        }
        @CustomType.Setter
        public Builder slug(String slug) {
            if (slug == null) {
              throw new MissingRequiredPropertyException("PageInfo", "slug");
            }
            this.slug = slug;
            return this;
        }
        @CustomType.Setter
        public Builder title(String title) {
            if (title == null) {
              throw new MissingRequiredPropertyException("PageInfo", "title");
            }
            this.title = title;
            return this;
        }
        public PageInfo build() {
            final var _resultValue = new PageInfo();
            _resultValue.archived = archived;
            _resultValue.collectionId = collectionId;
            _resultValue.createdOn = createdOn;
            _resultValue.draft = draft;
            _resultValue.lastUpdated = lastUpdated;
            _resultValue.pageId = pageId;
            _resultValue.parentId = parentId;
            _resultValue.siteId = siteId;
            _resultValue.slug = slug;
            _resultValue.title = title;
            return _resultValue;
        }
    }
}
