// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/webflow/Webflow/sdk/go/Webflow/internal"
)

var _ = internal.GetEnvOrDefault

// Webflow API v2 bearer token for authentication. Can also be set via WEBFLOW_API_TOKEN environment variable.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "webflow:token")
}
