name: Publish TypeScript SDK to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Perform dry-run publish (no actual publish)'
        required: false
        default: 'false'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish TypeScript SDK

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract version from release
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION=${{ github.event.release.tag_name }}
            VERSION=${VERSION#v}  # Remove 'v' prefix if present
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          else
            VERSION=$(cat sdk/nodejs/package.json | grep '"version"' | head -1 | sed 's/.*"version": "\(.*\)".*/\1/')
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        working-directory: sdk/nodejs
        run: npm ci

      - name: Build TypeScript SDK
        working-directory: sdk/nodejs
        run: npm run build

      - name: Validate package contents (dry-run)
        working-directory: sdk/nodejs
        run: npm publish --dry-run

      - name: Publish to npm (dry-run)
        working-directory: sdk/nodejs
        if: github.event.inputs.dry_run == 'true'
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm (production)
        working-directory: sdk/nodejs
        if: github.event_name == 'release' && github.event.action == 'published'
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify package on npm
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          sleep 5
          npm view pulumi-webflow@${{ steps.version.outputs.version }}

      - name: Create GitHub Release Asset
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sdk/nodejs/bin/**
            sdk/nodejs/package.json
          token: ${{ secrets.GITHUB_TOKEN }}
