# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'NodeContentUpdateArgs',
    'NodeContentUpdateArgsDict',
]

MYPY = False

if not MYPY:
    class NodeContentUpdateArgsDict(TypedDict):
        node_id: pulumi.Input[_builtins.str]
        """
        The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
        """
        text: pulumi.Input[_builtins.str]
        """
        The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
        """
elif False:
    NodeContentUpdateArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class NodeContentUpdateArgs:
    def __init__(__self__, *,
                 node_id: pulumi.Input[_builtins.str],
                 text: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] node_id: The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
        :param pulumi.Input[_builtins.str] text: The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
        """
        pulumi.set(__self__, "node_id", node_id)
        pulumi.set(__self__, "text", text)

    @_builtins.property
    @pulumi.getter(name="nodeId")
    def node_id(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
        """
        return pulumi.get(self, "node_id")

    @node_id.setter
    def node_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "node_id", value)

    @_builtins.property
    @pulumi.getter
    def text(self) -> pulumi.Input[_builtins.str]:
        """
        The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
        """
        return pulumi.get(self, "text")

    @text.setter
    def text(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "text", value)


