# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'PageInfo',
]

@pulumi.output_type
class PageInfo(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "createdOn":
            suggest = "created_on"
        elif key == "lastUpdated":
            suggest = "last_updated"
        elif key == "pageId":
            suggest = "page_id"
        elif key == "siteId":
            suggest = "site_id"
        elif key == "collectionId":
            suggest = "collection_id"
        elif key == "parentId":
            suggest = "parent_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PageInfo. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PageInfo.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PageInfo.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 archived: _builtins.bool,
                 created_on: _builtins.str,
                 draft: _builtins.bool,
                 last_updated: _builtins.str,
                 page_id: _builtins.str,
                 site_id: _builtins.str,
                 slug: _builtins.str,
                 title: _builtins.str,
                 collection_id: Optional[_builtins.str] = None,
                 parent_id: Optional[_builtins.str] = None):
        pulumi.set(__self__, "archived", archived)
        pulumi.set(__self__, "created_on", created_on)
        pulumi.set(__self__, "draft", draft)
        pulumi.set(__self__, "last_updated", last_updated)
        pulumi.set(__self__, "page_id", page_id)
        pulumi.set(__self__, "site_id", site_id)
        pulumi.set(__self__, "slug", slug)
        pulumi.set(__self__, "title", title)
        if collection_id is not None:
            pulumi.set(__self__, "collection_id", collection_id)
        if parent_id is not None:
            pulumi.set(__self__, "parent_id", parent_id)

    @_builtins.property
    @pulumi.getter
    def archived(self) -> _builtins.bool:
        return pulumi.get(self, "archived")

    @_builtins.property
    @pulumi.getter(name="createdOn")
    def created_on(self) -> _builtins.str:
        return pulumi.get(self, "created_on")

    @_builtins.property
    @pulumi.getter
    def draft(self) -> _builtins.bool:
        return pulumi.get(self, "draft")

    @_builtins.property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> _builtins.str:
        return pulumi.get(self, "last_updated")

    @_builtins.property
    @pulumi.getter(name="pageId")
    def page_id(self) -> _builtins.str:
        return pulumi.get(self, "page_id")

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> _builtins.str:
        return pulumi.get(self, "site_id")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> _builtins.str:
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter
    def title(self) -> _builtins.str:
        return pulumi.get(self, "title")

    @_builtins.property
    @pulumi.getter(name="collectionId")
    def collection_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "collection_id")

    @_builtins.property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "parent_id")


