// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Webflow.Outputs
{

    [OutputType]
    public sealed class GetTokenInfoAuthorizedTo
    {
        /// <summary>
        /// List of site IDs this token is authorized to access.
        /// </summary>
        public readonly ImmutableArray<string> SiteIds;
        /// <summary>
        /// List of user IDs this token is authorized to access.
        /// </summary>
        public readonly ImmutableArray<string> UserIds;
        /// <summary>
        /// List of workspace IDs this token is authorized to access.
        /// </summary>
        public readonly ImmutableArray<string> WorkspaceIds;

        [OutputConstructor]
        private GetTokenInfoAuthorizedTo(
            ImmutableArray<string> siteIds,

            ImmutableArray<string> userIds,

            ImmutableArray<string> workspaceIds)
        {
            SiteIds = siteIds;
            UserIds = userIds;
            WorkspaceIds = workspaceIds;
        }
    }
}
