// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Webflow.Outputs
{

    [OutputType]
    public sealed class GetTokenInfoApplication
    {
        /// <summary>
        /// The application description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The human-readable name of the application.
        /// </summary>
        public readonly string DisplayName;
        /// <summary>
        /// The application homepage URL.
        /// </summary>
        public readonly string Homepage;
        /// <summary>
        /// The unique identifier for the application.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetTokenInfoApplication(
            string description,

            string displayName,

            string homepage,

            string id)
        {
            Description = description;
            DisplayName = displayName;
            Homepage = homepage;
            Id = id;
        }
    }
}
