// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Webflow.Outputs
{

    [OutputType]
    public sealed class PageCustomCodeScript
    {
        /// <summary>
        /// Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Attributes;
        /// <summary>
        /// The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Where the script should be applied on the page. Must be either 'header' (loaded in page header) or 'footer' (loaded at end of page). Use 'header' for scripts that don't depend on DOM elements. Use 'footer' for scripts that need to run after DOM is fully loaded.
        /// </summary>
        public readonly string Location;
        /// <summary>
        /// The semantic version string for the registered script (e.g., '1.0.0'). This version must match a registered version of the script. You can have multiple versions of the same script registered.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private PageCustomCodeScript(
            ImmutableDictionary<string, object> attributes,

            string id,

            string location,

            string version)
        {
            Attributes = attributes;
            Id = id;
            Location = location;
            Version = version;
        }
    }
}
