// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AssetArgs extends com.pulumi.resources.ResourceArgs {

    public static final AssetArgs Empty = new AssetArgs();

    /**
     * MD5 hash of the file content (required). Webflow uses this hash to identify and deduplicate assets. Generate using: md5sum &lt;filename&gt; (Linux) or md5 &lt;filename&gt; (macOS). Example: &#39;d41d8cd98f00b204e9800998ecf8427e&#39;.
     * 
     */
    @Import(name="fileHash", required=true)
    private Output<String> fileHash;

    /**
     * @return MD5 hash of the file content (required). Webflow uses this hash to identify and deduplicate assets. Generate using: md5sum &lt;filename&gt; (Linux) or md5 &lt;filename&gt; (macOS). Example: &#39;d41d8cd98f00b204e9800998ecf8427e&#39;.
     * 
     */
    public Output<String> fileHash() {
        return this.fileHash;
    }

    /**
     * The name of the file to upload, including the extension. Examples: &#39;logo.png&#39;, &#39;hero-image.jpg&#39;, &#39;document.pdf&#39;. The file name must not exceed 255 characters and should not contain invalid characters (&lt;, &gt;, :, &#34;, |, ?, *).
     * 
     */
    @Import(name="fileName", required=true)
    private Output<String> fileName;

    /**
     * @return The name of the file to upload, including the extension. Examples: &#39;logo.png&#39;, &#39;hero-image.jpg&#39;, &#39;document.pdf&#39;. The file name must not exceed 255 characters and should not contain invalid characters (&lt;, &gt;, :, &#34;, |, ?, *).
     * 
     */
    public Output<String> fileName() {
        return this.fileName;
    }

    /**
     * The source of the file to upload. For the current implementation, this is a reference field. In future versions, this may support URLs or local file paths for automatic upload. Examples: &#39;https://example.com/logo.png&#39;, &#39;/path/to/local/file.png&#39;.
     * 
     */
    @Import(name="fileSource")
    private @Nullable Output<String> fileSource;

    /**
     * @return The source of the file to upload. For the current implementation, this is a reference field. In future versions, this may support URLs or local file paths for automatic upload. Examples: &#39;https://example.com/logo.png&#39;, &#39;/path/to/local/file.png&#39;.
     * 
     */
    public Optional<Output<String>> fileSource() {
        return Optional.ofNullable(this.fileSource);
    }

    /**
     * Optional folder ID where the asset will be organized in the Webflow Assets panel. If not specified, the asset will be placed at the root level. Example: &#39;5f0c8c9e1c9d440000e8d8c4&#39;.
     * 
     */
    @Import(name="parentFolder")
    private @Nullable Output<String> parentFolder;

    /**
     * @return Optional folder ID where the asset will be organized in the Webflow Assets panel. If not specified, the asset will be placed at the root level. Example: &#39;5f0c8c9e1c9d440000e8d8c4&#39;.
     * 
     */
    public Optional<Output<String>> parentFolder() {
        return Optional.ofNullable(this.parentFolder);
    }

    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Import(name="siteId", required=true)
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }

    private AssetArgs() {}

    private AssetArgs(AssetArgs $) {
        this.fileHash = $.fileHash;
        this.fileName = $.fileName;
        this.fileSource = $.fileSource;
        this.parentFolder = $.parentFolder;
        this.siteId = $.siteId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AssetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AssetArgs $;

        public Builder() {
            $ = new AssetArgs();
        }

        public Builder(AssetArgs defaults) {
            $ = new AssetArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param fileHash MD5 hash of the file content (required). Webflow uses this hash to identify and deduplicate assets. Generate using: md5sum &lt;filename&gt; (Linux) or md5 &lt;filename&gt; (macOS). Example: &#39;d41d8cd98f00b204e9800998ecf8427e&#39;.
         * 
         * @return builder
         * 
         */
        public Builder fileHash(Output<String> fileHash) {
            $.fileHash = fileHash;
            return this;
        }

        /**
         * @param fileHash MD5 hash of the file content (required). Webflow uses this hash to identify and deduplicate assets. Generate using: md5sum &lt;filename&gt; (Linux) or md5 &lt;filename&gt; (macOS). Example: &#39;d41d8cd98f00b204e9800998ecf8427e&#39;.
         * 
         * @return builder
         * 
         */
        public Builder fileHash(String fileHash) {
            return fileHash(Output.of(fileHash));
        }

        /**
         * @param fileName The name of the file to upload, including the extension. Examples: &#39;logo.png&#39;, &#39;hero-image.jpg&#39;, &#39;document.pdf&#39;. The file name must not exceed 255 characters and should not contain invalid characters (&lt;, &gt;, :, &#34;, |, ?, *).
         * 
         * @return builder
         * 
         */
        public Builder fileName(Output<String> fileName) {
            $.fileName = fileName;
            return this;
        }

        /**
         * @param fileName The name of the file to upload, including the extension. Examples: &#39;logo.png&#39;, &#39;hero-image.jpg&#39;, &#39;document.pdf&#39;. The file name must not exceed 255 characters and should not contain invalid characters (&lt;, &gt;, :, &#34;, |, ?, *).
         * 
         * @return builder
         * 
         */
        public Builder fileName(String fileName) {
            return fileName(Output.of(fileName));
        }

        /**
         * @param fileSource The source of the file to upload. For the current implementation, this is a reference field. In future versions, this may support URLs or local file paths for automatic upload. Examples: &#39;https://example.com/logo.png&#39;, &#39;/path/to/local/file.png&#39;.
         * 
         * @return builder
         * 
         */
        public Builder fileSource(@Nullable Output<String> fileSource) {
            $.fileSource = fileSource;
            return this;
        }

        /**
         * @param fileSource The source of the file to upload. For the current implementation, this is a reference field. In future versions, this may support URLs or local file paths for automatic upload. Examples: &#39;https://example.com/logo.png&#39;, &#39;/path/to/local/file.png&#39;.
         * 
         * @return builder
         * 
         */
        public Builder fileSource(String fileSource) {
            return fileSource(Output.of(fileSource));
        }

        /**
         * @param parentFolder Optional folder ID where the asset will be organized in the Webflow Assets panel. If not specified, the asset will be placed at the root level. Example: &#39;5f0c8c9e1c9d440000e8d8c4&#39;.
         * 
         * @return builder
         * 
         */
        public Builder parentFolder(@Nullable Output<String> parentFolder) {
            $.parentFolder = parentFolder;
            return this;
        }

        /**
         * @param parentFolder Optional folder ID where the asset will be organized in the Webflow Assets panel. If not specified, the asset will be placed at the root level. Example: &#39;5f0c8c9e1c9d440000e8d8c4&#39;.
         * 
         * @return builder
         * 
         */
        public Builder parentFolder(String parentFolder) {
            return parentFolder(Output.of(parentFolder));
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(Output<String> siteId) {
            $.siteId = siteId;
            return this;
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(String siteId) {
            return siteId(Output.of(siteId));
        }

        public AssetArgs build() {
            if ($.fileHash == null) {
                throw new MissingRequiredPropertyException("AssetArgs", "fileHash");
            }
            if ($.fileName == null) {
                throw new MissingRequiredPropertyException("AssetArgs", "fileName");
            }
            if ($.siteId == null) {
                throw new MissingRequiredPropertyException("AssetArgs", "siteId");
            }
            return $;
        }
    }

}
