// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CollectionItemArgs extends com.pulumi.resources.ResourceArgs {

    public static final CollectionItemArgs Empty = new CollectionItemArgs();

    /**
     * The locale ID for localized sites (optional, e.g., &#39;en-US&#39;). Only required if your site uses Webflow&#39;s localization features. Leave empty for non-localized sites.
     * 
     */
    @Import(name="cmsLocaleId")
    private @Nullable Output<String> cmsLocaleId;

    /**
     * @return The locale ID for localized sites (optional, e.g., &#39;en-US&#39;). Only required if your site uses Webflow&#39;s localization features. Leave empty for non-localized sites.
     * 
     */
    public Optional<Output<String>> cmsLocaleId() {
        return Optional.ofNullable(this.cmsLocaleId);
    }

    /**
     * The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
     * 
     */
    @Import(name="collectionId", required=true)
    private Output<String> collectionId;

    /**
     * @return The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
     * 
     */
    public Output<String> collectionId() {
        return this.collectionId;
    }

    /**
     * A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include &#39;name&#39; (required), &#39;slug&#39; (required, URL-friendly), and any custom fields you&#39;ve added to the collection. Example: {&#34;name&#34;: &#34;My Blog Post&#34;, &#34;slug&#34;: &#34;my-blog-post&#34;, &#34;content&#34;: &#34;Post content...&#34;}
     * 
     */
    @Import(name="fieldData", required=true)
    private Output<Map<String,Object>> fieldData;

    /**
     * @return A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include &#39;name&#39; (required), &#39;slug&#39; (required, URL-friendly), and any custom fields you&#39;ve added to the collection. Example: {&#34;name&#34;: &#34;My Blog Post&#34;, &#34;slug&#34;: &#34;my-blog-post&#34;, &#34;content&#34;: &#34;Post content...&#34;}
     * 
     */
    public Output<Map<String,Object>> fieldData() {
        return this.fieldData;
    }

    /**
     * Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
     * 
     */
    @Import(name="isArchived")
    private @Nullable Output<Boolean> isArchived;

    /**
     * @return Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
     * 
     */
    public Optional<Output<Boolean>> isArchived() {
        return Optional.ofNullable(this.isArchived);
    }

    /**
     * Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
     * 
     */
    @Import(name="isDraft")
    private @Nullable Output<Boolean> isDraft;

    /**
     * @return Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
     * 
     */
    public Optional<Output<Boolean>> isDraft() {
        return Optional.ofNullable(this.isDraft);
    }

    private CollectionItemArgs() {}

    private CollectionItemArgs(CollectionItemArgs $) {
        this.cmsLocaleId = $.cmsLocaleId;
        this.collectionId = $.collectionId;
        this.fieldData = $.fieldData;
        this.isArchived = $.isArchived;
        this.isDraft = $.isDraft;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CollectionItemArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CollectionItemArgs $;

        public Builder() {
            $ = new CollectionItemArgs();
        }

        public Builder(CollectionItemArgs defaults) {
            $ = new CollectionItemArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cmsLocaleId The locale ID for localized sites (optional, e.g., &#39;en-US&#39;). Only required if your site uses Webflow&#39;s localization features. Leave empty for non-localized sites.
         * 
         * @return builder
         * 
         */
        public Builder cmsLocaleId(@Nullable Output<String> cmsLocaleId) {
            $.cmsLocaleId = cmsLocaleId;
            return this;
        }

        /**
         * @param cmsLocaleId The locale ID for localized sites (optional, e.g., &#39;en-US&#39;). Only required if your site uses Webflow&#39;s localization features. Leave empty for non-localized sites.
         * 
         * @return builder
         * 
         */
        public Builder cmsLocaleId(String cmsLocaleId) {
            return cmsLocaleId(Output.of(cmsLocaleId));
        }

        /**
         * @param collectionId The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder collectionId(Output<String> collectionId) {
            $.collectionId = collectionId;
            return this;
        }

        /**
         * @param collectionId The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder collectionId(String collectionId) {
            return collectionId(Output.of(collectionId));
        }

        /**
         * @param fieldData A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include &#39;name&#39; (required), &#39;slug&#39; (required, URL-friendly), and any custom fields you&#39;ve added to the collection. Example: {&#34;name&#34;: &#34;My Blog Post&#34;, &#34;slug&#34;: &#34;my-blog-post&#34;, &#34;content&#34;: &#34;Post content...&#34;}
         * 
         * @return builder
         * 
         */
        public Builder fieldData(Output<Map<String,Object>> fieldData) {
            $.fieldData = fieldData;
            return this;
        }

        /**
         * @param fieldData A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include &#39;name&#39; (required), &#39;slug&#39; (required, URL-friendly), and any custom fields you&#39;ve added to the collection. Example: {&#34;name&#34;: &#34;My Blog Post&#34;, &#34;slug&#34;: &#34;my-blog-post&#34;, &#34;content&#34;: &#34;Post content...&#34;}
         * 
         * @return builder
         * 
         */
        public Builder fieldData(Map<String,Object> fieldData) {
            return fieldData(Output.of(fieldData));
        }

        /**
         * @param isArchived Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
         * 
         * @return builder
         * 
         */
        public Builder isArchived(@Nullable Output<Boolean> isArchived) {
            $.isArchived = isArchived;
            return this;
        }

        /**
         * @param isArchived Whether the item is archived (optional, defaults to false). Archived items are not visible on the published site but remain in the CMS.
         * 
         * @return builder
         * 
         */
        public Builder isArchived(Boolean isArchived) {
            return isArchived(Output.of(isArchived));
        }

        /**
         * @param isDraft Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
         * 
         * @return builder
         * 
         */
        public Builder isDraft(@Nullable Output<Boolean> isDraft) {
            $.isDraft = isDraft;
            return this;
        }

        /**
         * @param isDraft Whether the item is a draft (optional, defaults to true). Draft items are not published to the live site. Set to false to publish the item immediately upon creation.
         * 
         * @return builder
         * 
         */
        public Builder isDraft(Boolean isDraft) {
            return isDraft(Output.of(isDraft));
        }

        public CollectionItemArgs build() {
            if ($.collectionId == null) {
                throw new MissingRequiredPropertyException("CollectionItemArgs", "collectionId");
            }
            if ($.fieldData == null) {
                throw new MissingRequiredPropertyException("CollectionItemArgs", "fieldData");
            }
            return $;
        }
    }

}
