// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.webflow.PageDataArgs;
import io.github.jdetmar.pulumi.webflow.Utilities;
import io.github.jdetmar.pulumi.webflow.outputs.PageInfo;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Reads page information from a Webflow site. Pages cannot be created via the API - they must be created in the Webflow designer. Use this data source to retrieve page metadata for use in your infrastructure code. Specify pageId to get a single page, or omit it to list all pages in the site.
 * 
 */
@ResourceType(type="webflow:index:PageData")
public class PageData extends com.pulumi.resources.CustomResource {
    /**
     * Indicates if the page is archived (read-only). Only populated when pageId input is specified.
     * 
     */
    @Export(name="archived", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> archived;

    /**
     * @return Indicates if the page is archived (read-only). Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<Boolean>> archived() {
        return Codegen.optional(this.archived);
    }
    /**
     * The ID of the CMS collection (read-only, optional). Only present for collection pages. Only populated when pageId input is specified.
     * 
     */
    @Export(name="collectionId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> collectionId;

    /**
     * @return The ID of the CMS collection (read-only, optional). Only present for collection pages. Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<String>> collectionId() {
        return Codegen.optional(this.collectionId);
    }
    /**
     * The timestamp when the page was created (read-only, RFC3339 format). Only populated when pageId input is specified.
     * 
     */
    @Export(name="createdOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdOn;

    /**
     * @return The timestamp when the page was created (read-only, RFC3339 format). Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<String>> createdOn() {
        return Codegen.optional(this.createdOn);
    }
    /**
     * Indicates if the page is in draft mode (read-only). Only populated when pageId input is specified.
     * 
     */
    @Export(name="draft", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> draft;

    /**
     * @return Indicates if the page is in draft mode (read-only). Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<Boolean>> draft() {
        return Codegen.optional(this.draft);
    }
    /**
     * The timestamp when the page was last updated (read-only, RFC3339 format). Only populated when pageId input is specified.
     * 
     */
    @Export(name="lastUpdated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastUpdated;

    /**
     * @return The timestamp when the page was last updated (read-only, RFC3339 format). Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<String>> lastUpdated() {
        return Codegen.optional(this.lastUpdated);
    }
    /**
     * The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). If specified, only this page&#39;s data will be returned. If omitted, all pages for the site will be returned in the &#39;pages&#39; output.
     * 
     */
    @Export(name="pageId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> pageId;

    /**
     * @return The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). If specified, only this page&#39;s data will be returned. If omitted, all pages for the site will be returned in the &#39;pages&#39; output.
     * 
     */
    public Output<Optional<String>> pageId() {
        return Codegen.optional(this.pageId);
    }
    /**
     * List of all pages in the site (read-only). Only populated when pageId input is NOT specified. Each page includes all metadata fields: id, siteId, title, slug, createdOn, lastUpdated, archived, draft, and optional parentId/collectionId.
     * 
     */
    @Export(name="pages", refs={List.class,PageInfo.class}, tree="[0,1]")
    private Output</* @Nullable */ List<PageInfo>> pages;

    /**
     * @return List of all pages in the site (read-only). Only populated when pageId input is NOT specified. Each page includes all metadata fields: id, siteId, title, slug, createdOn, lastUpdated, archived, draft, and optional parentId/collectionId.
     * 
     */
    public Output<Optional<List<PageInfo>>> pages() {
        return Codegen.optional(this.pages);
    }
    /**
     * The ID of the parent page (read-only, optional). Only present for nested pages. Only populated when pageId input is specified.
     * 
     */
    @Export(name="parentId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> parentId;

    /**
     * @return The ID of the parent page (read-only, optional). Only present for nested pages. Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<String>> parentId() {
        return Codegen.optional(this.parentId);
    }
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Export(name="siteId", refs={String.class}, tree="[0]")
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }
    /**
     * The URL slug for the page (read-only, e.g., &#39;about&#39; for &#39;/about&#39;). Only populated when pageId input is specified.
     * 
     */
    @Export(name="slug", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> slug;

    /**
     * @return The URL slug for the page (read-only, e.g., &#39;about&#39; for &#39;/about&#39;). Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<String>> slug() {
        return Codegen.optional(this.slug);
    }
    /**
     * The page title (read-only). This is the title shown in browser tabs and search results. Only populated when pageId input is specified.
     * 
     */
    @Export(name="title", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> title;

    /**
     * @return The page title (read-only). This is the title shown in browser tabs and search results. Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<String>> title() {
        return Codegen.optional(this.title);
    }
    /**
     * The Webflow page ID (read-only). Only populated when pageId input is specified.
     * 
     */
    @Export(name="webflowPageId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> webflowPageId;

    /**
     * @return The Webflow page ID (read-only). Only populated when pageId input is specified.
     * 
     */
    public Output<Optional<String>> webflowPageId() {
        return Codegen.optional(this.webflowPageId);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PageData(java.lang.String name) {
        this(name, PageDataArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PageData(java.lang.String name, PageDataArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PageData(java.lang.String name, PageDataArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:PageData", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private PageData(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:PageData", name, null, makeResourceOptions(options, id), false);
    }

    private static PageDataArgs makeArgs(PageDataArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PageDataArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PageData get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PageData(name, id, options);
    }
}
