// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.webflow.PageContentArgs;
import io.github.jdetmar.pulumi.webflow.Utilities;
import io.github.jdetmar.pulumi.webflow.outputs.NodeContentUpdate;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages static content (text) for a Webflow page. This resource allows you to update text content within existing DOM nodes on a page. It does NOT manage page structure or layout - only content within existing nodes. To find node IDs, you must first retrieve the page DOM structure using the Webflow API.
 * 
 * **IMPORTANT LIMITATION:** This resource does NOT support drift detection for content changes. If content is modified outside of Pulumi (via Webflow UI or API), those changes will NOT be detected during &#39;pulumi refresh&#39; or &#39;pulumi up&#39;. The resource only verifies that the page still exists. This is due to the complexity of extracting and comparing specific node text from the full DOM structure.
 * 
 */
@ResourceType(type="webflow:index:PageContent")
public class PageContent extends com.pulumi.resources.CustomResource {
    /**
     * The timestamp when the page content was last updated (RFC3339 format). This is automatically set when content is updated and is read-only.
     * 
     */
    @Export(name="lastUpdated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastUpdated;

    /**
     * @return The timestamp when the page content was last updated (RFC3339 format). This is automatically set when content is updated and is read-only.
     * 
     */
    public Output<Optional<String>> lastUpdated() {
        return Codegen.optional(this.lastUpdated);
    }
    /**
     * List of node content updates to apply. Each update specifies the nodeId (from the page&#39;s DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
     * 
     */
    @Export(name="nodes", refs={List.class,NodeContentUpdate.class}, tree="[0,1]")
    private Output<List<NodeContentUpdate>> nodes;

    /**
     * @return List of node content updates to apply. Each update specifies the nodeId (from the page&#39;s DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
     * 
     */
    public Output<List<NodeContentUpdate>> nodes() {
        return this.nodes;
    }
    /**
     * The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
     * 
     */
    @Export(name="pageId", refs={String.class}, tree="[0]")
    private Output<String> pageId;

    /**
     * @return The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
     * 
     */
    public Output<String> pageId() {
        return this.pageId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PageContent(java.lang.String name) {
        this(name, PageContentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PageContent(java.lang.String name, PageContentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PageContent(java.lang.String name, PageContentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:PageContent", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private PageContent(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:PageContent", name, null, makeResourceOptions(options, id), false);
    }

    private static PageContentArgs makeArgs(PageContentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PageContentArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-webflow")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PageContent get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PageContent(name, id, options);
    }
}
