// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PageDataArgs extends com.pulumi.resources.ResourceArgs {

    public static final PageDataArgs Empty = new PageDataArgs();

    /**
     * The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). If specified, only this page&#39;s data will be returned. If omitted, all pages for the site will be returned in the &#39;pages&#39; output.
     * 
     */
    @Import(name="pageId")
    private @Nullable Output<String> pageId;

    /**
     * @return The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). If specified, only this page&#39;s data will be returned. If omitted, all pages for the site will be returned in the &#39;pages&#39; output.
     * 
     */
    public Optional<Output<String>> pageId() {
        return Optional.ofNullable(this.pageId);
    }

    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Import(name="siteId", required=true)
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }

    private PageDataArgs() {}

    private PageDataArgs(PageDataArgs $) {
        this.pageId = $.pageId;
        this.siteId = $.siteId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PageDataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PageDataArgs $;

        public Builder() {
            $ = new PageDataArgs();
        }

        public Builder(PageDataArgs defaults) {
            $ = new PageDataArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param pageId The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). If specified, only this page&#39;s data will be returned. If omitted, all pages for the site will be returned in the &#39;pages&#39; output.
         * 
         * @return builder
         * 
         */
        public Builder pageId(@Nullable Output<String> pageId) {
            $.pageId = pageId;
            return this;
        }

        /**
         * @param pageId The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). If specified, only this page&#39;s data will be returned. If omitted, all pages for the site will be returned in the &#39;pages&#39; output.
         * 
         * @return builder
         * 
         */
        public Builder pageId(String pageId) {
            return pageId(Output.of(pageId));
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(Output<String> siteId) {
            $.siteId = siteId;
            return this;
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(String siteId) {
            return siteId(Output.of(siteId));
        }

        public PageDataArgs build() {
            if ($.siteId == null) {
                throw new MissingRequiredPropertyException("PageDataArgs", "siteId");
            }
            return $;
        }
    }

}
