// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.inputs.PageCustomCodeScriptArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class PageCustomCodeArgs extends com.pulumi.resources.ResourceArgs {

    public static final PageCustomCodeArgs Empty = new PageCustomCodeArgs();

    /**
     * The Webflow page ID (24-character hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
     * 
     */
    @Import(name="pageId", required=true)
    private Output<String> pageId;

    /**
     * @return The Webflow page ID (24-character hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
     * 
     */
    public Output<String> pageId() {
        return this.pageId;
    }

    /**
     * List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
     * 
     */
    @Import(name="scripts", required=true)
    private Output<List<PageCustomCodeScriptArgs>> scripts;

    /**
     * @return List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
     * 
     */
    public Output<List<PageCustomCodeScriptArgs>> scripts() {
        return this.scripts;
    }

    private PageCustomCodeArgs() {}

    private PageCustomCodeArgs(PageCustomCodeArgs $) {
        this.pageId = $.pageId;
        this.scripts = $.scripts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PageCustomCodeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PageCustomCodeArgs $;

        public Builder() {
            $ = new PageCustomCodeArgs();
        }

        public Builder(PageCustomCodeArgs defaults) {
            $ = new PageCustomCodeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param pageId The Webflow page ID (24-character hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder pageId(Output<String> pageId) {
            $.pageId = pageId;
            return this;
        }

        /**
         * @param pageId The Webflow page ID (24-character hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder pageId(String pageId) {
            return pageId(Output.of(pageId));
        }

        /**
         * @param scripts List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
         * 
         * @return builder
         * 
         */
        public Builder scripts(Output<List<PageCustomCodeScriptArgs>> scripts) {
            $.scripts = scripts;
            return this;
        }

        /**
         * @param scripts List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
         * 
         * @return builder
         * 
         */
        public Builder scripts(List<PageCustomCodeScriptArgs> scripts) {
            return scripts(Output.of(scripts));
        }

        /**
         * @param scripts List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
         * 
         * @return builder
         * 
         */
        public Builder scripts(PageCustomCodeScriptArgs... scripts) {
            return scripts(List.of(scripts));
        }

        public PageCustomCodeArgs build() {
            if ($.pageId == null) {
                throw new MissingRequiredPropertyException("PageCustomCodeArgs", "pageId");
            }
            if ($.scripts == null) {
                throw new MissingRequiredPropertyException("PageCustomCodeArgs", "scripts");
            }
            return $;
        }
    }

}
