// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.webflow.RegisteredScriptArgs;
import io.github.jdetmar.pulumi.webflow.Utilities;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages custom code scripts in the Webflow script registry. This resource allows you to register and manage externally hosted scripts that can be deployed across your Webflow site with version control and integrity verification.
 * 
 */
@ResourceType(type="webflow:index:RegisteredScript")
public class RegisteredScript extends com.pulumi.resources.CustomResource {
    /**
     * Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
     * 
     */
    @Export(name="canCopy", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> canCopy;

    /**
     * @return Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
     * 
     */
    public Output<Optional<Boolean>> canCopy() {
        return Codegen.optional(this.canCopy);
    }
    /**
     * The timestamp when the script was created (RFC3339 format). This is automatically set by Webflow when the script is created and is read-only.
     * 
     */
    @Export(name="createdOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdOn;

    /**
     * @return The timestamp when the script was created (RFC3339 format). This is automatically set by Webflow when the script is created and is read-only.
     * 
     */
    public Output<Optional<String>> createdOn() {
        return Codegen.optional(this.createdOn);
    }
    /**
     * The user-facing name for the script (1-50 alphanumeric characters). This name is used to identify the script in the Webflow interface. Only letters (A-Z, a-z) and numbers (0-9) are allowed. Example valid names: &#39;CmsSlider&#39;, &#39;AnalyticsScript&#39;, &#39;MyCustomScript123&#39;.
     * 
     */
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output<String> displayName;

    /**
     * @return The user-facing name for the script (1-50 alphanumeric characters). This name is used to identify the script in the Webflow interface. Only letters (A-Z, a-z) and numbers (0-9) are allowed. Example valid names: &#39;CmsSlider&#39;, &#39;AnalyticsScript&#39;, &#39;MyCustomScript123&#39;.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }
    /**
     * The URI for the externally hosted script (e.g., &#39;https://cdn.example.com/my-script.js&#39;). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
     * 
     */
    @Export(name="hostedLocation", refs={String.class}, tree="[0]")
    private Output<String> hostedLocation;

    /**
     * @return The URI for the externally hosted script (e.g., &#39;https://cdn.example.com/my-script.js&#39;). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
     * 
     */
    public Output<String> hostedLocation() {
        return this.hostedLocation;
    }
    /**
     * The Sub-Resource Integrity (SRI) hash for the script. Format: &#39;sha384-&lt;hash&gt;&#39;, &#39;sha256-&lt;hash&gt;&#39;, or &#39;sha512-&lt;hash&gt;&#39;. SRI hashes help ensure that the script hasn&#39;t been modified in transit. You can generate an SRI hash using https://www.srihash.org/
     * 
     */
    @Export(name="integrityHash", refs={String.class}, tree="[0]")
    private Output<String> integrityHash;

    /**
     * @return The Sub-Resource Integrity (SRI) hash for the script. Format: &#39;sha384-&lt;hash&gt;&#39;, &#39;sha256-&lt;hash&gt;&#39;, or &#39;sha512-&lt;hash&gt;&#39;. SRI hashes help ensure that the script hasn&#39;t been modified in transit. You can generate an SRI hash using https://www.srihash.org/
     * 
     */
    public Output<String> integrityHash() {
        return this.integrityHash;
    }
    /**
     * The timestamp when the script was last updated (RFC3339 format). This is automatically updated by Webflow when the script is modified and is read-only.
     * 
     */
    @Export(name="lastUpdated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastUpdated;

    /**
     * @return The timestamp when the script was last updated (RFC3339 format). This is automatically updated by Webflow when the script is modified and is read-only.
     * 
     */
    public Output<Optional<String>> lastUpdated() {
        return Codegen.optional(this.lastUpdated);
    }
    /**
     * The Webflow-assigned script ID (read-only). This is typically the lowercase version of displayName. Use this value when referencing the script in SiteCustomCode or PageCustomCode resources.
     * 
     */
    @Export(name="scriptId", refs={String.class}, tree="[0]")
    private Output<String> scriptId;

    /**
     * @return The Webflow-assigned script ID (read-only). This is typically the lowercase version of displayName. Use this value when referencing the script in SiteCustomCode or PageCustomCode resources.
     * 
     */
    public Output<String> scriptId() {
        return this.scriptId;
    }
    /**
     * The Semantic Version (SemVer) string for the script (e.g., &#39;1.0.0&#39;, &#39;2.3.1&#39;). This helps track different versions of your script. See https://semver.org/ for more information on semantic versioning.
     * 
     */
    @Export(name="scriptVersion", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> scriptVersion;

    /**
     * @return The Semantic Version (SemVer) string for the script (e.g., &#39;1.0.0&#39;, &#39;2.3.1&#39;). This helps track different versions of your script. See https://semver.org/ for more information on semantic versioning.
     * 
     */
    public Output<Optional<String>> scriptVersion() {
        return Codegen.optional(this.scriptVersion);
    }
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Export(name="siteId", refs={String.class}, tree="[0]")
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RegisteredScript(java.lang.String name) {
        this(name, RegisteredScriptArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RegisteredScript(java.lang.String name, RegisteredScriptArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RegisteredScript(java.lang.String name, RegisteredScriptArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:RegisteredScript", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RegisteredScript(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:RegisteredScript", name, null, makeResourceOptions(options, id), false);
    }

    private static RegisteredScriptArgs makeArgs(RegisteredScriptArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RegisteredScriptArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-webflow")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RegisteredScript get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RegisteredScript(name, id, options);
    }
}
