// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UserArgs extends com.pulumi.resources.ResourceArgs {

    public static final UserArgs Empty = new UserArgs();

    /**
     * Access group slugs assigned to the user.
     * 
     */
    @Import(name="accessGroups")
    private @Nullable Output<List<String>> accessGroups;

    /**
     * @return Access group slugs assigned to the user.
     * 
     */
    public Optional<Output<List<String>>> accessGroups() {
        return Optional.ofNullable(this.accessGroups);
    }

    /**
     * The email address of the user.
     * 
     */
    @Import(name="email", required=true)
    private Output<String> email;

    /**
     * @return The email address of the user.
     * 
     */
    public Output<String> email() {
        return this.email;
    }

    /**
     * Display name for the user.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Display name for the user.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The Webflow site ID.
     * 
     */
    @Import(name="siteId", required=true)
    private Output<String> siteId;

    /**
     * @return The Webflow site ID.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }

    private UserArgs() {}

    private UserArgs(UserArgs $) {
        this.accessGroups = $.accessGroups;
        this.email = $.email;
        this.name = $.name;
        this.siteId = $.siteId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UserArgs $;

        public Builder() {
            $ = new UserArgs();
        }

        public Builder(UserArgs defaults) {
            $ = new UserArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessGroups Access group slugs assigned to the user.
         * 
         * @return builder
         * 
         */
        public Builder accessGroups(@Nullable Output<List<String>> accessGroups) {
            $.accessGroups = accessGroups;
            return this;
        }

        /**
         * @param accessGroups Access group slugs assigned to the user.
         * 
         * @return builder
         * 
         */
        public Builder accessGroups(List<String> accessGroups) {
            return accessGroups(Output.of(accessGroups));
        }

        /**
         * @param accessGroups Access group slugs assigned to the user.
         * 
         * @return builder
         * 
         */
        public Builder accessGroups(String... accessGroups) {
            return accessGroups(List.of(accessGroups));
        }

        /**
         * @param email The email address of the user.
         * 
         * @return builder
         * 
         */
        public Builder email(Output<String> email) {
            $.email = email;
            return this;
        }

        /**
         * @param email The email address of the user.
         * 
         * @return builder
         * 
         */
        public Builder email(String email) {
            return email(Output.of(email));
        }

        /**
         * @param name Display name for the user.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Display name for the user.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param siteId The Webflow site ID.
         * 
         * @return builder
         * 
         */
        public Builder siteId(Output<String> siteId) {
            $.siteId = siteId;
            return this;
        }

        /**
         * @param siteId The Webflow site ID.
         * 
         * @return builder
         * 
         */
        public Builder siteId(String siteId) {
            return siteId(Output.of(siteId));
        }

        public UserArgs build() {
            if ($.email == null) {
                throw new MissingRequiredPropertyException("UserArgs", "email");
            }
            if ($.siteId == null) {
                throw new MissingRequiredPropertyException("UserArgs", "siteId");
            }
            return $;
        }
    }

}
