// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.webflow.UserArgs;
import io.github.jdetmar.pulumi.webflow.Utilities;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * DEPRECATED: The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run &#34;pulumi state delete &lt;URN&gt;&#34; to clean up existing state.
 * 
 * @deprecated
 * The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run &#34;pulumi state delete &lt;URN&gt;&#34; to clean up existing state.
 * 
 */
@Deprecated /* The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run ""pulumi state delete <URN>"" to clean up existing state. */
@ResourceType(type="webflow:index:User")
public class User extends com.pulumi.resources.CustomResource {
    /**
     * Access group slugs assigned to the user.
     * 
     */
    @Export(name="accessGroups", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> accessGroups;

    /**
     * @return Access group slugs assigned to the user.
     * 
     */
    public Output<Optional<List<String>>> accessGroups() {
        return Codegen.optional(this.accessGroups);
    }
    /**
     * Timestamp when the user was created.
     * 
     */
    @Export(name="createdOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdOn;

    /**
     * @return Timestamp when the user was created.
     * 
     */
    public Output<Optional<String>> createdOn() {
        return Codegen.optional(this.createdOn);
    }
    /**
     * The email address of the user.
     * 
     */
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output<String> email;

    /**
     * @return The email address of the user.
     * 
     */
    public Output<String> email() {
        return this.email;
    }
    /**
     * Timestamp when the user was invited.
     * 
     */
    @Export(name="invitedOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> invitedOn;

    /**
     * @return Timestamp when the user was invited.
     * 
     */
    public Output<Optional<String>> invitedOn() {
        return Codegen.optional(this.invitedOn);
    }
    /**
     * Whether the user has verified their email.
     * 
     */
    @Export(name="isEmailVerified", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isEmailVerified;

    /**
     * @return Whether the user has verified their email.
     * 
     */
    public Output<Optional<Boolean>> isEmailVerified() {
        return Codegen.optional(this.isEmailVerified);
    }
    /**
     * Timestamp when the user last logged in.
     * 
     */
    @Export(name="lastLogin", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastLogin;

    /**
     * @return Timestamp when the user last logged in.
     * 
     */
    public Output<Optional<String>> lastLogin() {
        return Codegen.optional(this.lastLogin);
    }
    /**
     * Timestamp when the user was last updated.
     * 
     */
    @Export(name="lastUpdated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastUpdated;

    /**
     * @return Timestamp when the user was last updated.
     * 
     */
    public Output<Optional<String>> lastUpdated() {
        return Codegen.optional(this.lastUpdated);
    }
    /**
     * Display name for the user.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> name;

    /**
     * @return Display name for the user.
     * 
     */
    public Output<Optional<String>> name() {
        return Codegen.optional(this.name);
    }
    /**
     * The Webflow site ID.
     * 
     */
    @Export(name="siteId", refs={String.class}, tree="[0]")
    private Output<String> siteId;

    /**
     * @return The Webflow site ID.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }
    /**
     * The user&#39;s status.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> status;

    /**
     * @return The user&#39;s status.
     * 
     */
    public Output<Optional<String>> status() {
        return Codegen.optional(this.status);
    }
    /**
     * The Webflow-assigned user ID.
     * 
     */
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> userId;

    /**
     * @return The Webflow-assigned user ID.
     * 
     */
    public Output<Optional<String>> userId() {
        return Codegen.optional(this.userId);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public User(java.lang.String name) {
        this(name, UserArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public User(java.lang.String name, UserArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public User(java.lang.String name, UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:User", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private User(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:User", name, null, makeResourceOptions(options, id), false);
    }

    private static UserArgs makeArgs(UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? UserArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-webflow")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static User get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new User(name, id, options);
    }
}
