name: Setup Tools
description: Installs all tools (Go, Node, Python, .NET, Java, Pulumi, etc.) using mise

inputs:
  cache:
    description: Enable caching
    required: false
    default: "false"
  github_token:
    description: GitHub token
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      env:
        MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s
      with:
        version: 2025.11.6
        cache_save: ${{ inputs.cache }}
        github_token: ${{ inputs.github_token }}

    - name: Install mise tools
      shell: bash
      run: mise install

    - name: Force install golangci-lint v2
      shell: bash
      run: |
        # Remove any cached v1 version and install v2
        mise uninstall golangci-lint || true
        mise install golangci-lint@2.7.2
        mise reshim
        # Verify the correct version is installed
        echo "PATH contains: $(which golangci-lint)"
        golangci-lint version

    - name: Setup Go Cache
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        cache: ${{ inputs.cache }}
        cache-dependency-path: |
          provider/*.sum
          upstream/*.sum
          sdk/go/*.sum
          sdk/*.sum
          *.sum

    - name: Setup Node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        # we don't set node-version because we install with mise.
        # this step is needed to setup npm auth
        registry-url: https://registry.npmjs.org
