// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class CustomScriptArgs {
    /**
     * @return Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {&#39;data-config&#39;: &#39;my-value&#39;}. These attributes are passed directly to the script tag.
     * 
     */
    private @Nullable Map<String,Object> attributes;
    /**
     * @return The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: &#39;cms_slider&#39;, &#39;analytics&#39;, &#39;custom_widget&#39;
     * 
     */
    private String id;
    /**
     * @return The location where the script is placed on the page. Valid values: &#39;header&#39; (placed in the &lt;head&gt; section), &#39;footer&#39; (placed before &lt;/body&gt;). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
     * 
     */
    private String location;
    /**
     * @return The semantic version string for the registered script (e.g., &#39;1.0.0&#39;, &#39;0.1.2&#39;). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
     * 
     */
    private String scriptVersion;

    private CustomScriptArgs() {}
    /**
     * @return Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {&#39;data-config&#39;: &#39;my-value&#39;}. These attributes are passed directly to the script tag.
     * 
     */
    public Map<String,Object> attributes() {
        return this.attributes == null ? Map.of() : this.attributes;
    }
    /**
     * @return The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: &#39;cms_slider&#39;, &#39;analytics&#39;, &#39;custom_widget&#39;
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The location where the script is placed on the page. Valid values: &#39;header&#39; (placed in the &lt;head&gt; section), &#39;footer&#39; (placed before &lt;/body&gt;). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
     * 
     */
    public String location() {
        return this.location;
    }
    /**
     * @return The semantic version string for the registered script (e.g., &#39;1.0.0&#39;, &#39;0.1.2&#39;). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
     * 
     */
    public String scriptVersion() {
        return this.scriptVersion;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CustomScriptArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Map<String,Object> attributes;
        private String id;
        private String location;
        private String scriptVersion;
        public Builder() {}
        public Builder(CustomScriptArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attributes = defaults.attributes;
    	      this.id = defaults.id;
    	      this.location = defaults.location;
    	      this.scriptVersion = defaults.scriptVersion;
        }

        @CustomType.Setter
        public Builder attributes(@Nullable Map<String,Object> attributes) {

            this.attributes = attributes;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("CustomScriptArgs", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder location(String location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("CustomScriptArgs", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder scriptVersion(String scriptVersion) {
            if (scriptVersion == null) {
              throw new MissingRequiredPropertyException("CustomScriptArgs", "scriptVersion");
            }
            this.scriptVersion = scriptVersion;
            return this;
        }
        public CustomScriptArgs build() {
            final var _resultValue = new CustomScriptArgs();
            _resultValue.attributes = attributes;
            _resultValue.id = id;
            _resultValue.location = location;
            _resultValue.scriptVersion = scriptVersion;
            return _resultValue;
        }
    }
}
