// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.outputs.GetTokenInfoAuthorizedTo;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTokenInfoAuthorization {
    /**
     * @return The resources this token is authorized to access.
     * 
     */
    private GetTokenInfoAuthorizedTo authorizedTo;
    /**
     * @return The timestamp when this authorization was created (RFC3339 format).
     * 
     */
    private String createdOn;
    /**
     * @return The OAuth grant type used to obtain this token (e.g., &#39;authorization_code&#39;).
     * 
     */
    private String grantType;
    /**
     * @return The unique identifier for this authorization.
     * 
     */
    private String id;
    /**
     * @return The timestamp when this token was last used (RFC3339 format).
     * 
     */
    private String lastUsed;
    /**
     * @return The rate limit for this token in requests per minute.
     * 
     */
    private Integer rateLimit;
    /**
     * @return The OAuth scopes granted to this token (space or comma separated).
     * 
     */
    private String scope;

    private GetTokenInfoAuthorization() {}
    /**
     * @return The resources this token is authorized to access.
     * 
     */
    public GetTokenInfoAuthorizedTo authorizedTo() {
        return this.authorizedTo;
    }
    /**
     * @return The timestamp when this authorization was created (RFC3339 format).
     * 
     */
    public String createdOn() {
        return this.createdOn;
    }
    /**
     * @return The OAuth grant type used to obtain this token (e.g., &#39;authorization_code&#39;).
     * 
     */
    public String grantType() {
        return this.grantType;
    }
    /**
     * @return The unique identifier for this authorization.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The timestamp when this token was last used (RFC3339 format).
     * 
     */
    public String lastUsed() {
        return this.lastUsed;
    }
    /**
     * @return The rate limit for this token in requests per minute.
     * 
     */
    public Integer rateLimit() {
        return this.rateLimit;
    }
    /**
     * @return The OAuth scopes granted to this token (space or comma separated).
     * 
     */
    public String scope() {
        return this.scope;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTokenInfoAuthorization defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetTokenInfoAuthorizedTo authorizedTo;
        private String createdOn;
        private String grantType;
        private String id;
        private String lastUsed;
        private Integer rateLimit;
        private String scope;
        public Builder() {}
        public Builder(GetTokenInfoAuthorization defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.authorizedTo = defaults.authorizedTo;
    	      this.createdOn = defaults.createdOn;
    	      this.grantType = defaults.grantType;
    	      this.id = defaults.id;
    	      this.lastUsed = defaults.lastUsed;
    	      this.rateLimit = defaults.rateLimit;
    	      this.scope = defaults.scope;
        }

        @CustomType.Setter
        public Builder authorizedTo(GetTokenInfoAuthorizedTo authorizedTo) {
            if (authorizedTo == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorization", "authorizedTo");
            }
            this.authorizedTo = authorizedTo;
            return this;
        }
        @CustomType.Setter
        public Builder createdOn(String createdOn) {
            if (createdOn == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorization", "createdOn");
            }
            this.createdOn = createdOn;
            return this;
        }
        @CustomType.Setter
        public Builder grantType(String grantType) {
            if (grantType == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorization", "grantType");
            }
            this.grantType = grantType;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorization", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lastUsed(String lastUsed) {
            if (lastUsed == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorization", "lastUsed");
            }
            this.lastUsed = lastUsed;
            return this;
        }
        @CustomType.Setter
        public Builder rateLimit(Integer rateLimit) {
            if (rateLimit == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorization", "rateLimit");
            }
            this.rateLimit = rateLimit;
            return this;
        }
        @CustomType.Setter
        public Builder scope(String scope) {
            if (scope == null) {
              throw new MissingRequiredPropertyException("GetTokenInfoAuthorization", "scope");
            }
            this.scope = scope;
            return this;
        }
        public GetTokenInfoAuthorization build() {
            final var _resultValue = new GetTokenInfoAuthorization();
            _resultValue.authorizedTo = authorizedTo;
            _resultValue.createdOn = createdOn;
            _resultValue.grantType = grantType;
            _resultValue.id = id;
            _resultValue.lastUsed = lastUsed;
            _resultValue.rateLimit = rateLimit;
            _resultValue.scope = scope;
            return _resultValue;
        }
    }
}
