// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class PageCustomCodeScript {
    /**
     * @return Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
     * 
     */
    private Map<String,Object> attributes;
    /**
     * @return The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
     * 
     */
    private String id;
    /**
     * @return Where the script should be applied on the page. Must be either &#39;header&#39; (loaded in page header) or &#39;footer&#39; (loaded at end of page). Use &#39;header&#39; for scripts that don&#39;t depend on DOM elements. Use &#39;footer&#39; for scripts that need to run after DOM is fully loaded.
     * 
     */
    private String location;
    /**
     * @return The semantic version string for the registered script (e.g., &#39;1.0.0&#39;). This version must match a registered version of the script. You can have multiple versions of the same script registered.
     * 
     */
    private String scriptVersion;

    private PageCustomCodeScript() {}
    /**
     * @return Optional developer-specified key/value pairs for script attributes. These attributes can be used by the script to customize its behavior on this page.
     * 
     */
    public Map<String,Object> attributes() {
        return this.attributes;
    }
    /**
     * @return The unique identifier of a registered custom code script. This must be a script that was previously registered using the RegisteredScript resource. Script IDs are assigned by Webflow when the script is registered.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Where the script should be applied on the page. Must be either &#39;header&#39; (loaded in page header) or &#39;footer&#39; (loaded at end of page). Use &#39;header&#39; for scripts that don&#39;t depend on DOM elements. Use &#39;footer&#39; for scripts that need to run after DOM is fully loaded.
     * 
     */
    public String location() {
        return this.location;
    }
    /**
     * @return The semantic version string for the registered script (e.g., &#39;1.0.0&#39;). This version must match a registered version of the script. You can have multiple versions of the same script registered.
     * 
     */
    public String scriptVersion() {
        return this.scriptVersion;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PageCustomCodeScript defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,Object> attributes;
        private String id;
        private String location;
        private String scriptVersion;
        public Builder() {}
        public Builder(PageCustomCodeScript defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attributes = defaults.attributes;
    	      this.id = defaults.id;
    	      this.location = defaults.location;
    	      this.scriptVersion = defaults.scriptVersion;
        }

        @CustomType.Setter
        public Builder attributes(Map<String,Object> attributes) {
            if (attributes == null) {
              throw new MissingRequiredPropertyException("PageCustomCodeScript", "attributes");
            }
            this.attributes = attributes;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("PageCustomCodeScript", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder location(String location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("PageCustomCodeScript", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder scriptVersion(String scriptVersion) {
            if (scriptVersion == null) {
              throw new MissingRequiredPropertyException("PageCustomCodeScript", "scriptVersion");
            }
            this.scriptVersion = scriptVersion;
            return this;
        }
        public PageCustomCodeScript build() {
            final var _resultValue = new PageCustomCodeScript();
            _resultValue.attributes = attributes;
            _resultValue.id = id;
            _resultValue.location = location;
            _resultValue.scriptVersion = scriptVersion;
            return _resultValue;
        }
    }
}
