// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CustomScriptArgs {
    /**
     * Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {'data-config': 'my-value'}. These attributes are passed directly to the script tag.
     */
    attributes?: {[key: string]: string};
    /**
     * The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: 'cms_slider', 'analytics', 'custom_widget'
     */
    id: string;
    /**
     * The location where the script is placed on the page. Valid values: 'header' (placed in the <head> section), 'footer' (placed before </body>). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
     */
    location: string;
    /**
     * The semantic version string for the registered script (e.g., '1.0.0', '0.1.2'). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
     */
    version: string;
}

export interface NodeContentUpdate {
    /**
     * The unique identifier for the DOM node to update. This ID comes from the page's DOM structure and must exist on the page. Retrieve node IDs using GET /pages/{page_id}/dom endpoint.
     */
    nodeId: string;
    /**
     * The new text content for the node. This will replace the existing text content in the specified node. Only applicable to text nodes or elements containing text.
     */
    text: string;
}

export interface PageInfo {
    archived: boolean;
    collectionId?: string;
    createdOn: string;
    draft: boolean;
    lastUpdated: string;
    pageId: string;
    parentId?: string;
    siteId: string;
    slug: string;
    title: string;
}

