// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    public static class GetAuthorizedUser
    {
        /// <summary>
        /// Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user's credentials are being used. Requires the 'authorized_user:read' scope.
        /// </summary>
        public static Task<GetAuthorizedUserResult> InvokeAsync(GetAuthorizedUserArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAuthorizedUserResult>("webflow:index:getAuthorizedUser", args ?? new GetAuthorizedUserArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user's credentials are being used. Requires the 'authorized_user:read' scope.
        /// </summary>
        public static Output<GetAuthorizedUserResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAuthorizedUserResult>("webflow:index:getAuthorizedUser", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Retrieves information about the user who authorized the current Webflow API token. This is useful for auditing and understanding which user's credentials are being used. Requires the 'authorized_user:read' scope.
        /// </summary>
        public static Output<GetAuthorizedUserResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAuthorizedUserResult>("webflow:index:getAuthorizedUser", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetAuthorizedUserArgs : global::Pulumi.InvokeArgs
    {
        public GetAuthorizedUserArgs()
        {
        }
        public static new GetAuthorizedUserArgs Empty => new GetAuthorizedUserArgs();
    }


    [OutputType]
    public sealed class GetAuthorizedUserResult
    {
        /// <summary>
        /// The email address of the authorized user.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// The first name of the authorized user.
        /// </summary>
        public readonly string FirstName;
        /// <summary>
        /// The last name of the authorized user.
        /// </summary>
        public readonly string LastName;
        /// <summary>
        /// The unique identifier for the authorized user.
        /// </summary>
        public readonly string UserId;

        [OutputConstructor]
        private GetAuthorizedUserResult(
            string email,

            string firstName,

            string lastName,

            string userId)
        {
            Email = email;
            FirstName = firstName;
            LastName = lastName;
            UserId = userId;
        }
    }
}
