// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    /// <summary>
    /// Manages static content (text) for a Webflow page. This resource allows you to update text content within existing DOM nodes on a page. It does NOT manage page structure or layout - only content within existing nodes. To find node IDs, you must first retrieve the page DOM structure using the Webflow API.
    /// 
    /// **IMPORTANT LIMITATION:** This resource does NOT support drift detection for content changes. If content is modified outside of Pulumi (via Webflow UI or API), those changes will NOT be detected during 'pulumi refresh' or 'pulumi up'. The resource only verifies that the page still exists. This is due to the complexity of extracting and comparing specific node text from the full DOM structure.
    /// </summary>
    [WebflowResourceType("webflow:index:PageContent")]
    public partial class PageContent : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when the page content was last updated (RFC3339 format). This is automatically set when content is updated and is read-only.
        /// </summary>
        [Output("lastUpdated")]
        public Output<string?> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
        /// </summary>
        [Output("nodes")]
        public Output<ImmutableArray<Outputs.NodeContentUpdate>> Nodes { get; private set; } = null!;

        /// <summary>
        /// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
        /// </summary>
        [Output("pageId")]
        public Output<string> PageId { get; private set; } = null!;


        /// <summary>
        /// Create a PageContent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PageContent(string name, PageContentArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:PageContent", name, args ?? new PageContentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PageContent(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:PageContent", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PageContent resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PageContent Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PageContent(name, id, options);
        }
    }

    public sealed class PageContentArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodes", required: true)]
        private InputList<Inputs.NodeContentUpdateArgs>? _nodes;

        /// <summary>
        /// List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
        /// </summary>
        public InputList<Inputs.NodeContentUpdateArgs> Nodes
        {
            get => _nodes ?? (_nodes = new InputList<Inputs.NodeContentUpdateArgs>());
            set => _nodes = value;
        }

        /// <summary>
        /// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
        /// </summary>
        [Input("pageId", required: true)]
        public Input<string> PageId { get; set; } = null!;

        public PageContentArgs()
        {
        }
        public static new PageContentArgs Empty => new PageContentArgs();
    }
}
