// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    /// <summary>
    /// Reads page information from a Webflow site. Pages cannot be created via the API - they must be created in the Webflow designer. Use this data source to retrieve page metadata for use in your infrastructure code. Specify pageId to get a single page, or omit it to list all pages in the site.
    /// </summary>
    [WebflowResourceType("webflow:index:PageData")]
    public partial class PageData : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Indicates if the page is archived (read-only). Only populated when pageId input is specified.
        /// </summary>
        [Output("archived")]
        public Output<bool?> Archived { get; private set; } = null!;

        /// <summary>
        /// The ID of the CMS collection (read-only, optional). Only present for collection pages. Only populated when pageId input is specified.
        /// </summary>
        [Output("collectionId")]
        public Output<string?> CollectionId { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the page was created (read-only, RFC3339 format). Only populated when pageId input is specified.
        /// </summary>
        [Output("createdOn")]
        public Output<string?> CreatedOn { get; private set; } = null!;

        /// <summary>
        /// Indicates if the page is in draft mode (read-only). Only populated when pageId input is specified.
        /// </summary>
        [Output("draft")]
        public Output<bool?> Draft { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the page was last updated (read-only, RFC3339 format). Only populated when pageId input is specified.
        /// </summary>
        [Output("lastUpdated")]
        public Output<string?> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). If specified, only this page's data will be returned. If omitted, all pages for the site will be returned in the 'pages' output.
        /// </summary>
        [Output("pageId")]
        public Output<string?> PageId { get; private set; } = null!;

        /// <summary>
        /// List of all pages in the site (read-only). Only populated when pageId input is NOT specified. Each page includes all metadata fields: id, siteId, title, slug, createdOn, lastUpdated, archived, draft, and optional parentId/collectionId.
        /// </summary>
        [Output("pages")]
        public Output<ImmutableArray<Outputs.PageInfo>> Pages { get; private set; } = null!;

        /// <summary>
        /// The ID of the parent page (read-only, optional). Only present for nested pages. Only populated when pageId input is specified.
        /// </summary>
        [Output("parentId")]
        public Output<string?> ParentId { get; private set; } = null!;

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
        /// </summary>
        [Output("siteId")]
        public Output<string> SiteId { get; private set; } = null!;

        /// <summary>
        /// The URL slug for the page (read-only, e.g., 'about' for '/about'). Only populated when pageId input is specified.
        /// </summary>
        [Output("slug")]
        public Output<string?> Slug { get; private set; } = null!;

        /// <summary>
        /// The page title (read-only). This is the title shown in browser tabs and search results. Only populated when pageId input is specified.
        /// </summary>
        [Output("title")]
        public Output<string?> Title { get; private set; } = null!;

        /// <summary>
        /// The Webflow page ID (read-only). Only populated when pageId input is specified.
        /// </summary>
        [Output("webflowPageId")]
        public Output<string?> WebflowPageId { get; private set; } = null!;


        /// <summary>
        /// Create a PageData resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PageData(string name, PageDataArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:PageData", name, args ?? new PageDataArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PageData(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:PageData", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-webflow",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PageData resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PageData Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PageData(name, id, options);
        }
    }

    public sealed class PageDataArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). If specified, only this page's data will be returned. If omitted, all pages for the site will be returned in the 'pages' output.
        /// </summary>
        [Input("pageId")]
        public Input<string>? PageId { get; set; }

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
        /// </summary>
        [Input("siteId", required: true)]
        public Input<string> SiteId { get; set; } = null!;

        public PageDataArgs()
        {
        }
        public static new PageDataArgs Empty => new PageDataArgs();
    }
}
