// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow.Outputs
{

    [OutputType]
    public sealed class CustomScriptArgs
    {
        /// <summary>
        /// Optional developer-specified key/value pairs applied as HTML attributes to the script tag. Example: {'data-config': 'my-value'}. These attributes are passed directly to the script tag.
        /// </summary>
        public readonly ImmutableDictionary<string, object>? Attributes;
        /// <summary>
        /// The unique identifier of the registered custom code script. The script must first be registered to the site using the RegisterScript resource. Examples: 'cms_slider', 'analytics', 'custom_widget'
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The location where the script is placed on the page. Valid values: 'header' (placed in the &lt;head&gt; section), 'footer' (placed before &lt;/body&gt;). Scripts in the header execute before page content loads, while footer scripts execute after the page has loaded.
        /// </summary>
        public readonly string Location;
        /// <summary>
        /// The semantic version string for the registered script (e.g., '1.0.0', '0.1.2'). This version must exist for the registered script ID. When you update the version, a different version of the script will be applied.
        /// </summary>
        public readonly string ScriptVersion;

        [OutputConstructor]
        private CustomScriptArgs(
            ImmutableDictionary<string, object>? attributes,

            string id,

            string location,

            string scriptVersion)
        {
            Attributes = attributes;
            Id = id;
            Location = location;
            ScriptVersion = scriptVersion;
        }
    }
}
