// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { CollectionArgs } from "./collection";
export type Collection = import("./collection").Collection;
export const Collection: typeof import("./collection").Collection = null as any;
utilities.lazyLoad(exports, ["Collection"], () => require("./collection"));

export { PageDataArgs } from "./pageData";
export type PageData = import("./pageData").PageData;
export const PageData: typeof import("./pageData").PageData = null as any;
utilities.lazyLoad(exports, ["PageData"], () => require("./pageData"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RedirectArgs } from "./redirect";
export type Redirect = import("./redirect").Redirect;
export const Redirect: typeof import("./redirect").Redirect = null as any;
utilities.lazyLoad(exports, ["Redirect"], () => require("./redirect"));

export { RobotsTxtArgs } from "./robotsTxt";
export type RobotsTxt = import("./robotsTxt").RobotsTxt;
export const RobotsTxt: typeof import("./robotsTxt").RobotsTxt = null as any;
utilities.lazyLoad(exports, ["RobotsTxt"], () => require("./robotsTxt"));

export { SiteArgs } from "./site";
export type Site = import("./site").Site;
export const Site: typeof import("./site").Site = null as any;
utilities.lazyLoad(exports, ["Site"], () => require("./site"));

export { WebhookArgs } from "./webhook";
export type Webhook = import("./webhook").Webhook;
export const Webhook: typeof import("./webhook").Webhook = null as any;
utilities.lazyLoad(exports, ["Webhook"], () => require("./webhook"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "webflow:index:Collection":
                return new Collection(name, <any>undefined, { urn })
            case "webflow:index:PageData":
                return new PageData(name, <any>undefined, { urn })
            case "webflow:index:Redirect":
                return new Redirect(name, <any>undefined, { urn })
            case "webflow:index:RobotsTxt":
                return new RobotsTxt(name, <any>undefined, { urn })
            case "webflow:index:Site":
                return new Site(name, <any>undefined, { urn })
            case "webflow:index:Webhook":
                return new Webhook(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("webflow", "index", _module)
pulumi.runtime.registerResourcePackage("webflow", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:webflow") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
