// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AssetArgs } from "./asset";
export type Asset = import("./asset").Asset;
export const Asset: typeof import("./asset").Asset = null as any;
utilities.lazyLoad(exports, ["Asset"], () => require("./asset"));

export { AssetFolderArgs } from "./assetFolder";
export type AssetFolder = import("./assetFolder").AssetFolder;
export const AssetFolder: typeof import("./assetFolder").AssetFolder = null as any;
utilities.lazyLoad(exports, ["AssetFolder"], () => require("./assetFolder"));

export { CollectionArgs } from "./collection";
export type Collection = import("./collection").Collection;
export const Collection: typeof import("./collection").Collection = null as any;
utilities.lazyLoad(exports, ["Collection"], () => require("./collection"));

export { CollectionFieldArgs } from "./collectionField";
export type CollectionField = import("./collectionField").CollectionField;
export const CollectionField: typeof import("./collectionField").CollectionField = null as any;
utilities.lazyLoad(exports, ["CollectionField"], () => require("./collectionField"));

export { CollectionItemArgs } from "./collectionItem";
export type CollectionItem = import("./collectionItem").CollectionItem;
export const CollectionItem: typeof import("./collectionItem").CollectionItem = null as any;
utilities.lazyLoad(exports, ["CollectionItem"], () => require("./collectionItem"));

export { EcommerceSettingsArgs } from "./ecommerceSettings";
export type EcommerceSettings = import("./ecommerceSettings").EcommerceSettings;
export const EcommerceSettings: typeof import("./ecommerceSettings").EcommerceSettings = null as any;
utilities.lazyLoad(exports, ["EcommerceSettings"], () => require("./ecommerceSettings"));

export { GetAuthorizedUserArgs, GetAuthorizedUserResult } from "./getAuthorizedUser";
export const getAuthorizedUser: typeof import("./getAuthorizedUser").getAuthorizedUser = null as any;
export const getAuthorizedUserOutput: typeof import("./getAuthorizedUser").getAuthorizedUserOutput = null as any;
utilities.lazyLoad(exports, ["getAuthorizedUser","getAuthorizedUserOutput"], () => require("./getAuthorizedUser"));

export { GetTokenInfoArgs, GetTokenInfoResult } from "./getTokenInfo";
export const getTokenInfo: typeof import("./getTokenInfo").getTokenInfo = null as any;
export const getTokenInfoOutput: typeof import("./getTokenInfo").getTokenInfoOutput = null as any;
utilities.lazyLoad(exports, ["getTokenInfo","getTokenInfoOutput"], () => require("./getTokenInfo"));

export { InlineScriptArgs } from "./inlineScript";
export type InlineScript = import("./inlineScript").InlineScript;
export const InlineScript: typeof import("./inlineScript").InlineScript = null as any;
utilities.lazyLoad(exports, ["InlineScript"], () => require("./inlineScript"));

export { PageContentArgs } from "./pageContent";
export type PageContent = import("./pageContent").PageContent;
export const PageContent: typeof import("./pageContent").PageContent = null as any;
utilities.lazyLoad(exports, ["PageContent"], () => require("./pageContent"));

export { PageCustomCodeArgs } from "./pageCustomCode";
export type PageCustomCode = import("./pageCustomCode").PageCustomCode;
export const PageCustomCode: typeof import("./pageCustomCode").PageCustomCode = null as any;
utilities.lazyLoad(exports, ["PageCustomCode"], () => require("./pageCustomCode"));

export { PageDataArgs } from "./pageData";
export type PageData = import("./pageData").PageData;
export const PageData: typeof import("./pageData").PageData = null as any;
utilities.lazyLoad(exports, ["PageData"], () => require("./pageData"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RedirectArgs } from "./redirect";
export type Redirect = import("./redirect").Redirect;
export const Redirect: typeof import("./redirect").Redirect = null as any;
utilities.lazyLoad(exports, ["Redirect"], () => require("./redirect"));

export { RegisteredScriptArgs } from "./registeredScript";
export type RegisteredScript = import("./registeredScript").RegisteredScript;
export const RegisteredScript: typeof import("./registeredScript").RegisteredScript = null as any;
utilities.lazyLoad(exports, ["RegisteredScript"], () => require("./registeredScript"));

export { RobotsTxtArgs } from "./robotsTxt";
export type RobotsTxt = import("./robotsTxt").RobotsTxt;
export const RobotsTxt: typeof import("./robotsTxt").RobotsTxt = null as any;
utilities.lazyLoad(exports, ["RobotsTxt"], () => require("./robotsTxt"));

export { SiteArgs } from "./site";
export type Site = import("./site").Site;
export const Site: typeof import("./site").Site = null as any;
utilities.lazyLoad(exports, ["Site"], () => require("./site"));

export { SiteCustomCodeArgs } from "./siteCustomCode";
export type SiteCustomCode = import("./siteCustomCode").SiteCustomCode;
export const SiteCustomCode: typeof import("./siteCustomCode").SiteCustomCode = null as any;
utilities.lazyLoad(exports, ["SiteCustomCode"], () => require("./siteCustomCode"));

export { WebhookArgs } from "./webhook";
export type Webhook = import("./webhook").Webhook;
export const Webhook: typeof import("./webhook").Webhook = null as any;
utilities.lazyLoad(exports, ["Webhook"], () => require("./webhook"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "webflow:index:Asset":
                return new Asset(name, <any>undefined, { urn })
            case "webflow:index:AssetFolder":
                return new AssetFolder(name, <any>undefined, { urn })
            case "webflow:index:Collection":
                return new Collection(name, <any>undefined, { urn })
            case "webflow:index:CollectionField":
                return new CollectionField(name, <any>undefined, { urn })
            case "webflow:index:CollectionItem":
                return new CollectionItem(name, <any>undefined, { urn })
            case "webflow:index:EcommerceSettings":
                return new EcommerceSettings(name, <any>undefined, { urn })
            case "webflow:index:InlineScript":
                return new InlineScript(name, <any>undefined, { urn })
            case "webflow:index:PageContent":
                return new PageContent(name, <any>undefined, { urn })
            case "webflow:index:PageCustomCode":
                return new PageCustomCode(name, <any>undefined, { urn })
            case "webflow:index:PageData":
                return new PageData(name, <any>undefined, { urn })
            case "webflow:index:Redirect":
                return new Redirect(name, <any>undefined, { urn })
            case "webflow:index:RegisteredScript":
                return new RegisteredScript(name, <any>undefined, { urn })
            case "webflow:index:RobotsTxt":
                return new RobotsTxt(name, <any>undefined, { urn })
            case "webflow:index:Site":
                return new Site(name, <any>undefined, { urn })
            case "webflow:index:SiteCustomCode":
                return new SiteCustomCode(name, <any>undefined, { urn })
            case "webflow:index:Webhook":
                return new Webhook(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("webflow", "index", _module)
pulumi.runtime.registerResourcePackage("webflow", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:webflow") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
