// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages static content (text) for a Webflow page. This resource allows you to update text content within existing DOM nodes on a page. It does NOT manage page structure or layout - only content within existing nodes. To find node IDs, you must first retrieve the page DOM structure using the Webflow API.
 *
 * **IMPORTANT LIMITATION:** This resource does NOT support drift detection for content changes. If content is modified outside of Pulumi (via Webflow UI or API), those changes will NOT be detected during 'pulumi refresh' or 'pulumi up'. The resource only verifies that the page still exists. This is due to the complexity of extracting and comparing specific node text from the full DOM structure.
 */
export class PageContent extends pulumi.CustomResource {
    /**
     * Get an existing PageContent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PageContent {
        return new PageContent(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:PageContent';

    /**
     * Returns true if the given object is an instance of PageContent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PageContent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PageContent.__pulumiType;
    }

    /**
     * The timestamp when the page content was last updated (RFC3339 format). This is automatically set when content is updated and is read-only.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string | undefined>;
    /**
     * List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
     */
    declare public readonly nodes: pulumi.Output<outputs.NodeContentUpdate[]>;
    /**
     * The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
     */
    declare public readonly pageId: pulumi.Output<string>;

    /**
     * Create a PageContent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PageContentArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.nodes === undefined && !opts.urn) {
                throw new Error("Missing required property 'nodes'");
            }
            if (args?.pageId === undefined && !opts.urn) {
                throw new Error("Missing required property 'pageId'");
            }
            resourceInputs["nodes"] = args?.nodes;
            resourceInputs["pageId"] = args?.pageId;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        } else {
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["nodes"] = undefined /*out*/;
            resourceInputs["pageId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PageContent.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PageContent resource.
 */
export interface PageContentArgs {
    /**
     * List of node content updates to apply. Each update specifies the nodeId (from the page's DOM structure) and the new text content. Node IDs can be retrieved by fetching the page DOM using GET /pages/{page_id}/dom. Only text content in existing nodes can be updated via this resource.
     */
    nodes: pulumi.Input<pulumi.Input<inputs.NodeContentUpdateArgs>[]>;
    /**
     * The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Pages API list endpoint or in the Webflow designer. This field will be validated before making any API calls.
     */
    pageId: pulumi.Input<string>;
}
