// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Reads page information from a Webflow site. Pages cannot be created via the API - they must be created in the Webflow designer. Use this data source to retrieve page metadata for use in your infrastructure code. Specify pageId to get a single page, or omit it to list all pages in the site.
 */
export class PageData extends pulumi.CustomResource {
    /**
     * Get an existing PageData resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PageData {
        return new PageData(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:PageData';

    /**
     * Returns true if the given object is an instance of PageData.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PageData {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PageData.__pulumiType;
    }

    /**
     * Indicates if the page is archived (read-only). Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly archived: pulumi.Output<boolean | undefined>;
    /**
     * The ID of the CMS collection (read-only, optional). Only present for collection pages. Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly collectionId: pulumi.Output<string | undefined>;
    /**
     * The timestamp when the page was created (read-only, RFC3339 format). Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly createdOn: pulumi.Output<string | undefined>;
    /**
     * Indicates if the page is in draft mode (read-only). Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly draft: pulumi.Output<boolean | undefined>;
    /**
     * The timestamp when the page was last updated (read-only, RFC3339 format). Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string | undefined>;
    /**
     * The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). If specified, only this page's data will be returned. If omitted, all pages for the site will be returned in the 'pages' output.
     */
    declare public readonly pageId: pulumi.Output<string | undefined>;
    /**
     * List of all pages in the site (read-only). Only populated when pageId input is NOT specified. Each page includes all metadata fields: id, siteId, title, slug, createdOn, lastUpdated, archived, draft, and optional parentId/collectionId.
     */
    declare public /*out*/ readonly pages: pulumi.Output<outputs.PageInfo[] | undefined>;
    /**
     * The ID of the parent page (read-only, optional). Only present for nested pages. Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly parentId: pulumi.Output<string | undefined>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    declare public readonly siteId: pulumi.Output<string>;
    /**
     * The URL slug for the page (read-only, e.g., 'about' for '/about'). Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly slug: pulumi.Output<string | undefined>;
    /**
     * The page title (read-only). This is the title shown in browser tabs and search results. Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly title: pulumi.Output<string | undefined>;
    /**
     * The Webflow page ID (read-only). Only populated when pageId input is specified.
     */
    declare public /*out*/ readonly webflowPageId: pulumi.Output<string | undefined>;

    /**
     * Create a PageData resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PageDataArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.siteId === undefined && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["pageId"] = args?.pageId;
            resourceInputs["siteId"] = args?.siteId;
            resourceInputs["archived"] = undefined /*out*/;
            resourceInputs["collectionId"] = undefined /*out*/;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["draft"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["pages"] = undefined /*out*/;
            resourceInputs["parentId"] = undefined /*out*/;
            resourceInputs["slug"] = undefined /*out*/;
            resourceInputs["title"] = undefined /*out*/;
            resourceInputs["webflowPageId"] = undefined /*out*/;
        } else {
            resourceInputs["archived"] = undefined /*out*/;
            resourceInputs["collectionId"] = undefined /*out*/;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["draft"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["pageId"] = undefined /*out*/;
            resourceInputs["pages"] = undefined /*out*/;
            resourceInputs["parentId"] = undefined /*out*/;
            resourceInputs["siteId"] = undefined /*out*/;
            resourceInputs["slug"] = undefined /*out*/;
            resourceInputs["title"] = undefined /*out*/;
            resourceInputs["webflowPageId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PageData.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PageData resource.
 */
export interface PageDataArgs {
    /**
     * The specific page ID to retrieve (optional, 24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). If specified, only this page's data will be returned. If omitted, all pages for the site will be returned in the 'pages' output.
     */
    pageId?: pulumi.Input<string>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    siteId: pulumi.Input<string>;
}
