// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages custom JavaScript code applied to a Webflow site. This resource allows you to apply registered custom scripts to a site and control where they are placed (header or footer). Custom scripts must be registered to the site first via the RegisterScript resource.
 */
export class SiteCustomCode extends pulumi.CustomResource {
    /**
     * Get an existing SiteCustomCode resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SiteCustomCode {
        return new SiteCustomCode(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:SiteCustomCode';

    /**
     * Returns true if the given object is an instance of SiteCustomCode.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteCustomCode {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteCustomCode.__pulumiType;
    }

    /**
     * The timestamp when the site's custom code was first created (RFC3339 format). This is automatically set when custom code is first applied and is read-only.
     */
    public /*out*/ readonly createdOn!: pulumi.Output<string | undefined>;
    /**
     * The timestamp when the site's custom code was last updated (RFC3339 format). This is automatically set and is read-only.
     */
    public /*out*/ readonly lastUpdated!: pulumi.Output<string | undefined>;
    /**
     * A list of custom scripts to apply to the site. Each script must be registered to the site first. To remove individual scripts, simply exclude them from this list on the next update. If you have multiple scripts your app manages, ensure they are always included in this list.
     */
    public readonly scripts!: pulumi.Output<outputs.CustomScriptArgs[]>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    public readonly siteId!: pulumi.Output<string>;

    /**
     * Create a SiteCustomCode resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteCustomCodeArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.scripts === undefined) && !opts.urn) {
                throw new Error("Missing required property 'scripts'");
            }
            if ((!args || args.siteId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["scripts"] = args ? args.scripts : undefined;
            resourceInputs["siteId"] = args ? args.siteId : undefined;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        } else {
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["scripts"] = undefined /*out*/;
            resourceInputs["siteId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteCustomCode.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SiteCustomCode resource.
 */
export interface SiteCustomCodeArgs {
    /**
     * A list of custom scripts to apply to the site. Each script must be registered to the site first. To remove individual scripts, simply exclude them from this list on the next update. If you have multiple scripts your app manages, ensure they are always included in this list.
     */
    scripts: pulumi.Input<pulumi.Input<inputs.CustomScriptArgsArgs>[]>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    siteId: pulumi.Input<string>;
}
