// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * DEPRECATED: The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run "pulumi state delete <URN>" to clean up existing state.
 *
 * @deprecated The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run "pulumi state delete <URN>" to clean up existing state.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): User {
        pulumi.log.warn("User is deprecated: The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run \"pulumi state delete \u003cURN\u003e\" to clean up existing state.")
        return new User(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Access group slugs assigned to the user.
     */
    public readonly accessGroups!: pulumi.Output<string[] | undefined>;
    /**
     * Timestamp when the user was created.
     */
    public /*out*/ readonly createdOn!: pulumi.Output<string | undefined>;
    /**
     * The email address of the user.
     */
    public readonly email!: pulumi.Output<string>;
    /**
     * Timestamp when the user was invited.
     */
    public /*out*/ readonly invitedOn!: pulumi.Output<string | undefined>;
    /**
     * Whether the user has verified their email.
     */
    public /*out*/ readonly isEmailVerified!: pulumi.Output<boolean | undefined>;
    /**
     * Timestamp when the user last logged in.
     */
    public /*out*/ readonly lastLogin!: pulumi.Output<string | undefined>;
    /**
     * Timestamp when the user was last updated.
     */
    public /*out*/ readonly lastUpdated!: pulumi.Output<string | undefined>;
    /**
     * Display name for the user.
     */
    public readonly name!: pulumi.Output<string | undefined>;
    /**
     * The Webflow site ID.
     */
    public readonly siteId!: pulumi.Output<string>;
    /**
     * The user's status.
     */
    public /*out*/ readonly status!: pulumi.Output<string | undefined>;
    /**
     * The Webflow-assigned user ID.
     */
    public /*out*/ readonly userId!: pulumi.Output<string | undefined>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    /** @deprecated The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run "pulumi state delete <URN>" to clean up existing state. */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions) {
        pulumi.log.warn("User is deprecated: The webflow:index:User resource has been removed because the Webflow User Management API has been deprecated by Webflow. Please remove this resource from your Pulumi program and run \"pulumi state delete \u003cURN\u003e\" to clean up existing state.")
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.email === undefined) && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if ((!args || args.siteId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["accessGroups"] = args ? args.accessGroups : undefined;
            resourceInputs["email"] = args ? args.email : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["siteId"] = args ? args.siteId : undefined;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["invitedOn"] = undefined /*out*/;
            resourceInputs["isEmailVerified"] = undefined /*out*/;
            resourceInputs["lastLogin"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["accessGroups"] = undefined /*out*/;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["invitedOn"] = undefined /*out*/;
            resourceInputs["isEmailVerified"] = undefined /*out*/;
            resourceInputs["lastLogin"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["siteId"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Access group slugs assigned to the user.
     */
    accessGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The email address of the user.
     */
    email: pulumi.Input<string>;
    /**
     * Display name for the user.
     */
    name?: pulumi.Input<string>;
    /**
     * The Webflow site ID.
     */
    siteId: pulumi.Input<string>;
}
