// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages users for a Webflow site. This resource allows you to invite users to your site with specified access groups. Users will receive an invitation email and must accept it to access paid content. Note: The user's email cannot be changed after creation.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type 'admin' (assigned via API or designer). Example: ['premium-members', 'beta-testers']. Access group slugs can be found in the Webflow dashboard under Users > Access Groups.
     */
    declare public readonly accessGroups: pulumi.Output<string[] | undefined>;
    /**
     * The timestamp when the user was created (RFC3339 format). This is automatically set and is read-only.
     */
    declare public /*out*/ readonly createdOn: pulumi.Output<string | undefined>;
    /**
     * The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The timestamp when the user was invited (RFC3339 format). This is automatically set and is read-only.
     */
    declare public /*out*/ readonly invitedOn: pulumi.Output<string | undefined>;
    /**
     * Indicates whether the user has verified their email address. This is read-only and set by Webflow when the user verifies their email.
     */
    declare public /*out*/ readonly isEmailVerified: pulumi.Output<boolean | undefined>;
    /**
     * The timestamp when the user last logged in (RFC3339 format). This is read-only.
     */
    declare public /*out*/ readonly lastLogin: pulumi.Output<string | undefined>;
    /**
     * The timestamp when the user was last updated (RFC3339 format). This is read-only.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string | undefined>;
    /**
     * Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    declare public readonly siteId: pulumi.Output<string>;
    /**
     * The status of the user. Possible values: 'invited' (invitation sent but not accepted), 'verified' (email verified), 'unverified' (registered but email not verified). This is read-only.
     */
    declare public /*out*/ readonly status: pulumi.Output<string | undefined>;
    /**
     * The Webflow-assigned unique identifier for this user. This is automatically assigned when the user is created and is read-only.
     */
    declare public /*out*/ readonly userId: pulumi.Output<string | undefined>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.siteId === undefined && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["accessGroups"] = args?.accessGroups;
            resourceInputs["email"] = args?.email;
            resourceInputs["name"] = args?.name;
            resourceInputs["siteId"] = args?.siteId;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["invitedOn"] = undefined /*out*/;
            resourceInputs["isEmailVerified"] = undefined /*out*/;
            resourceInputs["lastLogin"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["accessGroups"] = undefined /*out*/;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["invitedOn"] = undefined /*out*/;
            resourceInputs["isEmailVerified"] = undefined /*out*/;
            resourceInputs["lastLogin"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["siteId"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Optional list of access group slugs to assign to the user. Access groups control what content the user can access. Groups are assigned as type 'admin' (assigned via API or designer). Example: ['premium-members', 'beta-testers']. Access group slugs can be found in the Webflow dashboard under Users > Access Groups.
     */
    accessGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The email address of the user to invite. The user will receive an invitation email at this address. IMPORTANT: The email cannot be changed after the user is created. Changing the email will require replacing the resource (delete + recreate).
     */
    email: pulumi.Input<string>;
    /**
     * Optional display name for the user. This will be shown in the Webflow dashboard and can be used in site personalization.
     */
    name?: pulumi.Input<string>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    siteId: pulumi.Input<string>;
}
